package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AACT_TRX_BASE") 
@Data 
public class AACT_TRX_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private int bookHrt; 
private String buseoNo; 
private String actMach; 
private int jakiAmt; 
private int bsCnt; 
private String georCd; 
private String actEvntCdCtt; 
private String updEmpNo; 
private String actCd; 
private int voucherNo; 
private String cdsngNo; 
private String trxBr; 
private String sts; 
private int canHisno; 
private Date updDt; 
private String ibTime; 
private String mgrNo; 
private Date canIl; 
private String regEmpNo; 
private String opNo; 
private Date gisIl; 
private int etc3Amt; 
private int hisNo; 
private String actAplyDvCd; 
private int ccyCnt; 
private Date ibIl; 
private int usdAmt; 
private String dpydGb; 
private String vipGb; 
private String actDseq; 
private String actCcy; 
private int basicHrt; 
private String ifrsDvCd; 
private String idNo; 
private String globId; 
private String plAddYn; 
private String upmuCd; 
private int fdcHdamt; 
private int etc1Amt; 
private String actDtyp; 
private int applHrt; 
private int actAmt; 
private Date acIl; 
private String posKind; 
private String actBsplGb; 
private String refNo; 
private String ibfGb; 
private int plCnt; 
private int etc2Amt; 
private int gosiHrt; 
private int demiHrt; 
private String actOvrdAplyCd; 
private Date regDt; 
private String ibjiMd; 
private String rmNo; 
private int trxSeq; 
private Date trxIl; 
private String cixNo; 
private String actCjum; 
private String actMode; 
private int fdcAmt; 
private String theirRefno; 
private String actTell; 
private String ilgeGb; 
private String actSjum; 
private String updTm; 
private String regTm; 
} 
