package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AACT_TRX_PL") 
@Data 
public class AACT_TRX_PLInfo implements Serializable { 
@Id 
@GeneratedValue 
private int oFeeFamt; 
private String georCd; 
private String gamGb; 
private int oFeeBamt; 
private String updEmpNo; 
private String ydGb; 
private String oDsCcy; 
private String sDsCcy; 
private String plCd; 
private int sApplHrt; 
private int pApplHrt; 
private String ibjiCd; 
private String pstGb; 
private Date updDt; 
private String pCcy; 
private Date oToIl; 
private int oIlsu; 
private String regEmpNo; 
private String docId; 
private int hisNo; 
private int sFeeBamt; 
private int sBasicHrt; 
private int sFeeFamt; 
private int pFtpRt; 
private int oApplHrt; 
private String jukiGb; 
private int pGosiHrt; 
private int pBasicHrt; 
private String slipGb; 
private String feeCd; 
private int sDemiHrt; 
private String ifrsDvCd; 
private String idNo; 
private String refNo2; 
private String orgGb; 
private String posGb; 
private String upmuCd; 
private int sBookHrt; 
private int segSeq; 
private int pBookHrt; 
private int sIlsu; 
private Date actIl; 
private int oIntRt; 
private String refNo; 
private String ibfGb; 
private int ydHisno; 
private int oDsAmt; 
private int sDsAmt; 
private String remark; 
private Date regDt; 
private int sFtpRt; 
private Date oFromIl; 
private String plCcy; 
private int sIntRt; 
private int pBamt; 
private int oFtpRt; 
private String cixNo; 
private int pFamt; 
private String ydRefno; 
private Date sFromIl; 
private int sGosiHrt; 
private String theirRefno; 
private String ilgeGb; 
private int pDemiHrt; 
private String updTm; 
private Date sToIl; 
private String actBr; 
private String regTm; 
} 
