package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ACOM_LMT_BASEHIS") 
@Data 
public class ACOM_LMT_BASEHISInfo implements Serializable { 
@Id 
@GeneratedValue 
private int silWoijan; 
private String trCd; 
private int woiGaetrm; 
private String woiSutgb; 
private int graceDay; 
private String mngNo; 
private String updEmpNo; 
private int sngAbtamt; 
private String condSts; 
private String actCd; 
private String sngBrno; 
private String ikCixno; 
private String actRtjo; 
private String sngAuth; 
private int bojBcnt; 
private String sngClerk; 
private String isSngno; 
private Date updDt; 
private String sngJumjang; 
private Date expIl; 
private int bojFcnt; 
private String sngAstmgr; 
private String sngNo; 
private int expMm; 
private Date canIl; 
private String sngCond; 
private String regEmpNo; 
private String opNo; 
private Date gisIl; 
private int silDjgjan; 
private String isBrno; 
private int hisNo; 
private int actRate; 
private Date ibIl; 
private String busiDayRule; 
private String trTime; 
private String agreeNo; 
private String revolGb; 
private String mngBr; 
private String dayCntBasis; 
private int woiYongdo; 
private String hisGb; 
private Date ikIl; 
private String sngSts; 
private String ikSngno; 
private int actAmt; 
private String sdBr; 
private String woiSunhu; 
private int bojMjAmt; 
private int silCnt; 
private Date acIl; 
private int woiInttrm; 
private String rateJugi; 
private String isCixno; 
private String sngCcy; 
private String sisSngno; 
private int sngAbtrt; 
private int actSprd; 
private String sngChajang; 
private int spread; 
private int penalRate; 
private String pogwlGb; 
private Date regDt; 
private int silJanamt; 
private int yoncheRate; 
private int sngAmt; 
private String cixNo; 
private String actRtgb; 
private String sngInfo; 
private int bojBjan; 
private int bojFjan; 
private String rateGb; 
private String ikBrno; 
private Date isIl; 
private Date silLstil; 
private int sngAplseq; 
private String gihanGb; 
private String trBr; 
private Date sngIl; 
private String sngLonmgr; 
private Date lstIbil; 
private String updTm; 
private int silAccum; 
private String regTm; 
} 
