package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ACOM_DMH_BASE") 
@Data 
public class ACOM_DMH_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private int famt; 
private String grtIdNo; 
private String updEmpNo; 
private int priority; 
private int famtInt; 
private String damboCity; 
private String systemGb; 
private String sts; 
private String damboAddr; 
private Date updDt; 
private String certNo; 
private int fstAppValueInt; 
private String insurRemark; 
private Date expireDate; 
private String regEmpNo; 
private String opNo; 
private int fstAppValue; 
private Date damboExpDate; 
private String filingNum; 
private int firstFixAmtExt; 
private String collOwnerName; 
private int fstAppValueExt; 
private int firstFixAmt; 
private String damboGurYn; 
private int grtPortion; 
private Date stsExpDate; 
private String insurObjAddr; 
private String mngBr; 
private String appraiserType; 
private Date fstAppDateInt; 
private int allocAmt; 
private String certSts; 
private String fixSts; 
private String insurCode; 
private String acctNo; 
private String issueNm; 
private String stCoGb; 
private String damboCd; 
private Date acIl; 
private int insurAmt; 
private int seqNo; 
private String damboType; 
private Date insurExpDate; 
private Date reAppDate; 
private String insurPolicyNo; 
private int lstHisNo; 
private String appAppraiser; 
private int famtExt; 
private Date filingDate; 
private Date lstAcIl; 
private Date regDt; 
private String damboCntGb; 
private String stCoName; 
private int firstFixAmtInt; 
private String certType; 
private String offerGb; 
private String cixNo; 
private int allocRatio; 
private Date fstAppDateExt; 
private String toMortgage; 
private String depositCd; 
private Date fstAppDate; 
private String judicialScrivener; 
private String damboNo; 
private int reAppValue; 
private int appGap; 
private int appLandValue; 
private String ccy; 
private int obankFixAmt; 
private String insurCompany; 
private String updTm; 
private String regTm; 
} 
