package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ACOM_CIX_BASE") 
@Data 
public class ACOM_CIX_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private String jobPlace; 
private String idTp; 
private String corpTp; 
private String updEmpNo; 
private Date lstDt; 
private String cixCd; 
private String mainTelNo; 
private String addrHnm23; 
private String addrHnm22; 
private String addrHnm24; 
private String hqCixNo; 
private Date updDt; 
private String custEnm; 
private String addrHnm21; 
private String jobCorres; 
private String jobPlcAddr2; 
private String jobPlcAddr3; 
private String jobPlcAddr1; 
private String regEmpNo; 
private String opNo; 
private String dmclCtryCd; 
private Date openDt; 
private String custSnm; 
private String ydGuja; 
private String postNo2; 
private String mobileNo; 
private String addrHnm1; 
private String addrHnm3; 
private String addrHnm2; 
private String addrHnm4; 
private String gyumoCd; 
private String jobPos; 
private String jobYear; 
private String postNo; 
private String marriageYn; 
private String idNo; 
private int profitExTax; 
private String hqIdNo; 
private String telNo; 
private String addrEnm4; 
private String addrEnm3; 
private Date endIdDt; 
private String idNm; 
private String addrEnm2; 
private String addrEnm1; 
private String lstBr; 
private String ctryCd; 
private String upjoCd; 
private int amtEmployee; 
private Date birthDt; 
private String custHnm; 
private String creditGrade; 
private String houseOwnYn; 
private String mailTp; 
private int salesScale; 
private String jobCtryCd; 
private String birthPlace; 
private String occupSince; 
private String jobMon; 
private String bicCd; 
private Date regDt; 
private String jobPlcAddr4; 
private String mngInfo; 
private int pdinCaptl; 
private String openBr; 
private String telNo2; 
private String mailAddr3; 
private String mailAddr2; 
private String emailAddr; 
private String jobPostNo; 
private int asset; 
private String mailAddr4; 
private String cixNo; 
private String sexCd; 
private String mailAddr1; 
private String remarks2; 
private String custHsnm; 
private String faxNo; 
private String remarks1; 
private String idNoKor; 
private String jobCd; 
private String updTm; 
private int capital; 
private String regTm; 
} 
