package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ACOM_LMT_BASEHD") 
@Data 
public class ACOM_LMT_BASEHDInfo implements Serializable { 
@Id 
@GeneratedValue 
private int woiGaetrm; 
private String woiSutgb; 
private int graceDay; 
private String updEmpNo; 
private int sngAbtamt; 
private String condSts; 
private int totBojBjan; 
private Date totSilLstil; 
private String sngBrno; 
private int totBojFjan; 
private String ikCixno; 
private String sngAuth; 
private String sngClerk; 
private String isSngno; 
private Date updDt; 
private String sngJumjang; 
private Date fstIl; 
private Date expIl; 
private String sngAstmgr; 
private String sngNo; 
private Date lstIl; 
private int expMm; 
private Date canIl; 
private String sngCond; 
private String regEmpNo; 
private String isBrno; 
private String busiDayRule; 
private String agreeNo; 
private String revolGb; 
private int totSilJanamt; 
private String mngBr; 
private String dayCntBasis; 
private int woiYongdo; 
private int totSilAccum; 
private Date ikIl; 
private String sngSts; 
private String ikSngno; 
private String woiSunhu; 
private int bojMjAmt; 
private int woiInttrm; 
private String rateJugi; 
private String isCixno; 
private String sngCcy; 
private String sisSngno; 
private int sngAbtrt; 
private String sngChajang; 
private int spread; 
private int penalRate; 
private String pogwlGb; 
private Date regDt; 
private int yoncheRate; 
private int sngAmt; 
private String cixNo; 
private String sngInfo; 
private int totSilCnt; 
private String rateGb; 
private String ikBrno; 
private Date isIl; 
private int sngAplseq; 
private String gihanGb; 
private Date sngIl; 
private int totBojBcnt; 
private String sngLonmgr; 
private int totBojFcnt; 
private Date lstIbil; 
private String updTm; 
private int totSilDjgjan; 
private String regTm; 
} 
