package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ACOM_COMH_MSG") 
@Data 
public class ACOM_COMH_MSGInfo implements Serializable { 
@Id 
@GeneratedValue 
private String lstTty; 
private String coBknm3; 
private String beDoc; 
private String coBknm4; 
private String prioYn; 
private String apTime; 
private String updEmpNo; 
private String condSts; 
private String coBknm1; 
private Date apIl; 
private Date tkeyIl; 
private String tkeyVal; 
private String tlxMngNo; 
private String relDoc; 
private String coBknm2; 
private String tkeyBkcd; 
private String ansBack; 
private String afDoc; 
private String inoutTime; 
private String tkeyYn; 
private String tkeyVar; 
private String morNo; 
private Date updDt; 
private String doneTime; 
private String branPrint; 
private String userKey; 
private Date lstIl; 
private String regEmpNo; 
private String docId; 
private String opNo; 
private String telexNo; 
private String prevMor; 
private String ourRef; 
private String dupYn; 
private String lstTime; 
private String msgType; 
private String tkeyCni1; 
private String lstOpNo; 
private String coBkcd; 
private Date inoutIl; 
private String physDivi; 
private int msgAmt; 
private String tkeyCni2; 
private String ioGb; 
private String globId; 
private String errMsg; 
private String upmuGb; 
private String tkeyPref; 
private int seqNo; 
private String brNo; 
private String flag1; 
private String prevTs; 
private String flag2; 
private String flag3; 
private Date regDt; 
private String msgGb; 
private String trailGb; 
private Date doneIl; 
private String prevMir; 
private String apMngNo; 
private String tsKey; 
private String netwGb; 
private String msgCcy; 
private String tkeyLine; 
private String typeGb; 
private String theirRef; 
private Date makeIl; 
private String headPrint; 
private String mirNo; 
private Date prevIl; 
private String updTm; 
private String msgFileNm; 
private String regTm; 
} 
