package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ADST_LNB_ITM") 
@Data 
public class ADST_LNB_ITMInfo implements Serializable { 
@Id 
@GeneratedValue 
private String trCd; 
private String afAutoDebitYn; 
private int bfLastChgRt; 
private int bfSpreadRt; 
private String afActGb; 
private Date afNxRollIl; 
private String afSchGb; 
private int afRollGap; 
private String sts; 
private Date updDt; 
private String bfAdvArrGb; 
private String bfAccrType; 
private Date bfNxRollIl; 
private String regEmpNo; 
private int afRepayGap; 
private int bfRollGap; 
private String bfLastChgYn; 
private String afSpreadGb; 
private String afLastChgYn; 
private String afAdvArrGb; 
private String afIntAdjYn; 
private Date bfTotExpIl; 
private Date afTotExpIl; 
private String bfIntAdjYn; 
private String bfNewSchYn; 
private String afRepayGb; 
private int afLastChgRt; 
private int afRepayAdjSeq; 
private String afNewSchYn; 
private String bfActGb; 
private String bfNxtSchYn; 
private int afNxtRt; 
private String afNxtSchYn; 
private int afSpreadRt; 
private String afAccrualGb; 
private int afIntGap; 
private String bfAccrualGb; 
private int afEvidAmt; 
private String afSingleBothType; 
private String bfRepayGb; 
private String bfRateChgYn; 
private String bfRepayGapGb; 
private String itmCd; 
private String bfEvidNo; 
private Date fstIbIl; 
private int bfGraceDays; 
private String bfIntGapGb; 
private String afIntGapGb; 
private int afGraceDays; 
private int bfLstRt; 
private String updEmpNo; 
private int bfIntGap; 
private Date bfRealExpIl; 
private String afBsnsDayRule; 
private int bfRepayGap; 
private int afRepayTerm; 
private String afPrnYcGb; 
private String bfEvidCcy; 
private int bfRepayTerm; 
private int afIntAdjSeq; 
private String afIntYcGb; 
private String afRepayGapGb; 
private String afRollGapGb; 
private int afGuchTerm; 
private String afFixFltGb; 
private String bfFixFltGb; 
private int afLstRt; 
private int hisNo; 
private Date bfPrnYcIl; 
private Date bfIntYcIl; 
private String afEvidCcy; 
private String bfSingleBothType; 
private int bfPastDueRt; 
private String bfSpreadGb; 
private String bfSchGb; 
private int bfTimesPast; 
private int afPastDueRt; 
private int bfGuchTerm; 
private String afAccrType; 
private Date afRealExpIl; 
private String bfAutoDebitYn; 
private String refNo; 
private Date afPrnYcIl; 
private int bfIntAdjSeq; 
private Date afIntYcIl; 
private String bfBsnsDayRule; 
private String bfRollGapGb; 
private String bfPrnYcGb; 
private Date lstAcIl; 
private Date regDt; 
private String afEvidNo; 
private int bfEvidAmt; 
private String bfIntYcGb; 
private Date lstIbIl; 
private String afRateChgYn; 
private int bfNxtRt; 
private int bfAccrualRt; 
private int bfRepayAdjSeq; 
private int afTimesPast; 
private int afAccrualRt; 
private String updTm; 
private String regTm; 
} 
