package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "ADST_LNB_BASE")
@Data
public class ADST_LNB_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String ikisSts;
    private String bkGb;
    private String cixNo;
    private String buseoNo;
    private String comId;
    private String comNm;
    private Date openIl;
    private Date totExpIl;
    private Date realExpIl;
    private Date fstExpIl;
    private String lonCcy;
    private int fstLonAmt;
    private int lonJan;
    private String repayGb;
    private String schGb;
    private String termGb;
    private String accrualGb;
    private String actGb;
    private int guchTerm;
    private int repayTerm;
    private int repayGap;
    private String repayGapGb;
    private int graceDays;
    private int repayCnt;
    private Date fstRepayIl;
    private Date lstRepayIl;
    private Date nxRepayIl;
    private Date lstIsuIl;
    private Date lstIibIl;
    private Date nxIsuIl;
    private Date nxRollIl;
    private Date lstBillIl;
    private Date nxBillIl;
    private int lstRt;
    private int misuAmt;
    private int misuSeq;
    private int mkjAmt;
    private int mkjSeq;
    private int repayAdjSeq;
    private int repayNxSeq;
    private int intAdjSeq;
    private int intNxSeq;
    private String prnYcGb;
    private Date prnYcIl;
    private String intYcGb;
    private Date intYcIl;
    private int ycGun;
    private int timesPastDueCnt;
    private int regPayAmt;
    private String nonEqGb;
    private int nonEqAmt;
    private String rateCcy;
    private String fixFltGb;
    private String spreadGb;
    private int spreadRt;
    private String rateChgYn;
    private int rollGap;
    private String rollGapGb;
    private String lateChgYn;
    private int lateChgRt;
    private int pastDueRt;
    private int accrualRt;
    private String capRtYn;
    private int capRtLife;
    private int capRtPrd;
    private String floorRtYn;
    private int floorRtLife;
    private int floorRtPrd;
    private String advArrGb;
    private String singleBothType;
    private String accrType;
    private String bsnsDayRule;
    private int intGap;
    private String intGapGb;
    private String intAdjYn;
    private int allInYield;
    private String hdSngNo;
    private String feeYn;
    private int appliFee;
    private int origiFee;
    private int renewFee;
    private int brokaFee;
    private int otherFee;
    private String sndDocNo;
    private String thrRcvDepoCcy;
    private String thrRcvDepoBic;
    private String evidNo;
    private String evidCcy;
    private int evidAmt;
    private int usdCvtAmt;
    private int bbsCvtAmt;
    private String autoDebitYn;
    private int lossAmt;
    private String restructuringYn;
    private Date fstIbIl;
    private Date lstDealIl;
    private Date lstIbIl;
    private String opNo;
    private String ownerNo;
    private String rmpbNo;
    private String ibfGb;
    private String blNo;
    private Date lgOpenIl;
    private int nxtRt;
    private String nxtSchYn;
    private String newSchYn;
    private Date msgLstIsuIl;
    private String agrRefNo;
    private int agrSeqNo;
    private String longShortType;
    private String flatSliding;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String partialYn;
    private Date partialExpiDt;
    private int partialAmt;
    private int partialJan;
    private String lnPrpsCd;
} 
