package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "adstDpbBase")
@Data
public class ADST_DPB_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String acctNo;
    private String baseCcy;
    private String acctCcy;
    private String dptBbsCd;
    private String dptBsCd;
    private String dptPlCd;
    private String intPayGb;
    private String dptTypeGb;
    private BigDecimal intTermGb;
    private String intCalGb;
    private String intCalMethCd;
    private String daysCalcMethCd;
    private Date opnIl;
    private Date jagumIl;
    private Date dptIntCalIl;
    private Date janCertiIl;
    private Date isIl;
    private Date ysdIl;
    private Date ccNgIl;
    private Date dptManIl;
    private Date rollOverIl;
    private String pwd;
    private String empPayAcctPwd;
    private BigDecimal bsJan;
    private BigDecimal curJan;
    private BigDecimal collatAmt;
    private BigDecimal openAmt;
    private BigDecimal clsAmt;
    private BigDecimal stopAmt;
    private BigDecimal lmtBlkAmt;
    private BigDecimal mTerm;
    private BigDecimal dTerm;
    private BigDecimal intPayCnt;
    private BigDecimal dptBasicRt;
    private BigDecimal dptNegoRt;
    private String taxCd;
    private BigDecimal taxRt;
    private String ftpRtGb;
    private BigDecimal ftpRt;
    private BigDecimal lstTrxNo;
    private BigDecimal lstDrTrxNo;
    private BigDecimal clsCnt;
    private String lonBbsCd;
    private String lonBsCd;
    private String lonPlCd;
    private BigDecimal fstJan;
    private BigDecimal maxJan;
    private BigDecimal lonSngAmt;
    private BigDecimal colLonInt;
    private BigDecimal lonPrcpYcInt;
    private BigDecimal lonIntYcInt;
    private String lonYdCd;
    private String lonRtCd;
    private BigDecimal lonRt;
    private BigDecimal prcpOverDueIntRt;
    private BigDecimal intOverDueIntRt;
    private Date lonIntCalIl;
    private Date lonIntRcvIl;
    private Date lonManIl;
    private Date lonTermIl;
    private Date lonFstYcIl;
    private Date lstIbIl;
    private String lstTime;
    private Date selfMngIl;
    private BigDecimal openExptAmt;
    private BigDecimal dueAmt;
    private BigDecimal depCnt;
    private BigDecimal prepayDay;
    private Date noticeIl;
    private String acctType;
    private String reserved1;
    private String intRtDv;
    private BigDecimal bfTmInt;
    private BigDecimal bfTmTax;
    private BigDecimal amt1;
    private BigDecimal amt2;
    private BigDecimal amt3;
    private BigDecimal amt4;
    private BigDecimal amt5;
    private BigDecimal amt6;
    private BigDecimal amt7;
    private BigDecimal amt8;
    private BigDecimal amt9;
    private BigDecimal amt10;
    private String cd1;
    private String cd2;
    private String cd3;
    private String cd4;
    private String cd5;
    private String cd6;
    private String cd7;
    private String cd8;
    private String cd9;
    private String cd10;
    private BigDecimal rt1;
    private BigDecimal rt2;
    private BigDecimal rt3;
    private BigDecimal rt4;
    private BigDecimal rt5;
    private Date dt1;
    private Date dt2;
    private Date dt3;
    private Date dt4;
    private Date dt5;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String randSalt;
} 
