package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ADST_LNB_AGR") 
@Data 
public class ADST_LNB_AGRInfo implements Serializable { 
@Id 
@GeneratedValue 
private String buseoNo; 
private String updEmpNo; 
private String repayGb; 
private String intGapGb; 
private String rcvDepoCcy; 
private int bbsCvtAmt; 
private String comNm; 
private String blNo; 
private Date lstDealIl; 
private Date updDt; 
private String spreadGb; 
private int usdCvtAmt; 
private String restructuringYn; 
private String regEmpNo; 
private String opNo; 
private int pastDueRt; 
private String ownerNo; 
private String evidNo; 
private Date totExpIl; 
private Date lgOpenIl; 
private String rcvDepoBic; 
private int spreadRt; 
private Date contractIl; 
private int indexRt; 
private String advArrGb; 
private String payDepoCcy; 
private String hdSngNo; 
private String evidCcy; 
private int drawdownSeq; 
private Date valueIl; 
private String accrType; 
private int lossAmt; 
private int intGap; 
private int rollGap; 
private int graceDays; 
private String fixFltGb; 
private String bkGb; 
private int lateChgRt; 
private String singleBothType; 
private String refNo; 
private String intAdjYn; 
private String ibfGb; 
private String commitfeeYn; 
private int feeRt; 
private String payDepoBic; 
private int repayGap; 
private Date regDt; 
private String rollGapGb; 
private String bsnsDayRule; 
private String yield; 
private String ikisSts; 
private int contractAmt; 
private String loanClass; 
private Date lstIbIl; 
private String comId; 
private String cixNo; 
private int evidAmt; 
private Date fstIbIl; 
private int repayCnt; 
private String substsCd; 
private String repayGapGb; 
private String rmpbNo; 
private String lonCcy; 
private int repayTerm; 
private int lonJan; 
private String updTm; 
private int blockAmt; 
private String rateCcy; 
private String regTm; 
} 
