package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ADST_DPB_TRAN") 
@Data 
public class ADST_DPB_TRANInfo implements Serializable { 
@Id 
@GeneratedValue 
private String oldTrxNo; 
private int dptRt; 
private int bookHrt; 
private int trxNo; 
private String trCd; 
private int pjHrt; 
private String updEmpNo; 
private String ydGb; 
private String reqCustId; 
private int tax3Amt; 
private int check3Aamt; 
private String cashTrGb; 
private String mechGb; 
private int tax1Amt; 
private int dptRtSngNo; 
private Date toDt; 
private String sts; 
private Date updDt; 
private String fxTrGb; 
private Date selfMngIl; 
private int etcFee1; 
private Date fromDt; 
private String ibgmSlipGb; 
private String noPbookGb; 
private String ibjiGb; 
private int tax2Amt; 
private int check2Aamt; 
private String regEmpNo; 
private String opNo; 
private Date gisIl; 
private String ydRefNo; 
private int chnlHisNo; 
private int hisNo; 
private int exRtSngNo; 
private String lstTime; 
private int intPayCnt; 
private int afJan; 
private Date ibIl; 
private int check1Aamt; 
private String trTime; 
private String tseqNo; 
private Date bfIntRcvIl; 
private String slipGb; 
private int trAamt; 
private String mngBr; 
private int basicHrt; 
private String trCcy; 
private String taxSlipGb; 
private String ydTheirRefNo; 
private String jigbYdGb; 
private String chkYdGb; 
private String sdBk; 
private int totFee; 
private int applHrt; 
private String acctNo; 
private String intSlipGb; 
private String subTrCd; 
private Date acIl; 
private String noPrintGb; 
private int check3Amt; 
private String chkGb; 
private int gosiHrt; 
private int demiHrt; 
private String remark; 
private Date regDt; 
private int trAmt; 
private int check2Amt; 
private Date lstIbIl; 
private String chnlRefNo; 
private String printGb; 
private String trBk; 
private int ydHisNo; 
private int cashFee; 
private String chkNo; 
private String fedDocId; 
private int check1Amt; 
private String trBr; 
private int tax4Amt; 
private Date bfIntCalIl; 
private String updTm; 
private String muinjaGb; 
private String fundGb; 
private String regTm; 
} 
