package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ADST_DPB_BASE") 
@Data 
public class ADST_DPB_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private int LON_INT_YC_INT; 
private int DPT_NEGO_RT; 
private int BF_TM_INT; 
private int STOP_AMT; 
private int LMT_BLK_AMT; 
private int LST_TRX_NO; 
private Date UPD_DT; 
private String LON_YD_CD; 
private String PWD; 
private int PREPAY_DAY; 
private String REG_EMP_NO; 
private String LON_BS_CD; 
private Date LON_INT_CAL_IL; 
private Date LON_TERM_IL; 
private String LST_TIME; 
private int INT_PAY_CNT; 
private int RT1; 
private int RT3; 
private int RT2; 
private int RT5; 
private int RT4; 
private int OPEN_EXPT_AMT; 
private Date DPT_INT_CAL_IL; 
private int CLS_CNT; 
private String INT_PAY_GB; 
private int PRCP_OVER_DUE_INT_RT; 
private Date LON_FST_YC_IL; 
private String ACCT_CCY; 
private String INT_CAL_METH_CD; 
private String DPT_BBS_CD; 
private Date ROLL_OVER_IL; 
private int DPT_BASIC_RT; 
private int BF_TM_TAX; 
private Date LON_INT_RCV_IL; 
private Date DPT_MAN_IL; 
private String INT_RT_DV; 
private Date OPN_IL; 
private int MAX_JAN; 
private int BS_JAN; 
private String INT_CAL_GB; 
private int CLS_AMT; 
private String CD10; 
private int TAX_RT; 
private int FTP_RT; 
private String DPT_PL_CD; 
private Date IS_IL; 
private Date CC_NG_IL; 
private int AMT10; 
private int DEP_CNT; 
private String TAX_CD; 
private int LON_PRCP_YC_INT; 
private String UPD_EMP_NO; 
private Date YSD_IL; 
private int AMT8; 
private int AMT9; 
private int AMT6; 
private int DUE_AMT; 
private int AMT7; 
private int AMT4; 
private int INT_TERM_GB; 
private int AMT5; 
private int AMT2; 
private int AMT3; 
private String BASE_CCY; 
private int OPEN_AMT; 
private int AMT1; 
private Date JAN_CERTI_IL; 
private String RAND_SALT; 
private Date SELF_MNG_IL; 
private String DPT_TYPE_GB; 
private Date DT1; 
private String RESERVED1; 
private Date DT3; 
private Date DT2; 
private String DPT_BS_CD; 
private Date DT5; 
private int CUR_JAN; 
private Date DT4; 
private Date NOTICE_IL; 
private String ACCT_TYPE; 
private String EMP_PAY_ACCT_PWD; 
private Date JAGUM_IL; 
private int FST_JAN; 
private String LON_BBS_CD; 
private int COLLAT_AMT; 
private int LST_DR_TRX_NO; 
private Date LON_MAN_IL; 
private String ACCT_NO; 
private int INT_OVER_DUE_INT_RT; 
private String LON_RT_CD; 
private int M_TERM; 
private int COL_LON_INT; 
private Date REG_DT; 
private String FTP_RT_GB; 
private Date LST_IB_IL; 
private String LON_PL_CD; 
private int D_TERM; 
private int LON_SNG_AMT; 
private String CD2; 
private String CD1; 
private String CD4; 
private String CD3; 
private String CD6; 
private String CD5; 
private String CD8; 
private String CD7; 
private int LON_RT; 
private String CD9; 
private String DAYS_CALC_METH_CD; 
private String UPD_TM; 
private String REG_TM; 
} 
