package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "adstDpbInfo")
@Data
public class ADST_DPB_INFOInfo implements Serializable {
    @Id
    @GeneratedValue
    private String acctNo;
    private String opnSayuCd;
    private String opnSrcCd;
    private String clsSayuCd;
    private String opnGb;
    private String clsGb;
    private String dormantYn;
    private String blYn;
    private String empPayAcctYn;
    private String lonIntCalGb;
    private String rollOverCd;
    private String roBaseDtCd;
    private String adminFeeExmpYn;
    private String clsFeeExmpYn;
    private String clsIntPayYn;
    private String sdAcctNo;
    private String pbookGb;
    private String pbookCd;
    private BigDecimal pbookLine;
    private BigDecimal pbookSeq;
    private BigDecimal pwdErrCnt;
    private String opNo;
    private String ownerNo;
    private String pbrmNo;
    private String pbookLossGb;
    private String stopWithGb;
    private String stopWith2Gb;
    private String stopDepGb;
    private String coltGb;
    private String warnLttrCd;
    private String warnCkNo;
    private String lstWarnCkNo;
    private Date warnRegDt;
    private Date lstWarnRegDt;
    private String ikIng;
    private String pbookUseGb;
    private String lonAcctGb;
    private String hoijun;
    private String intMoveGb;
    private String clsMoveGb;
    private String dptNegoRtGb;
    private String fixFltGb;
    private String vostroGb;
    private String jointRelCd;
    private String jointCixNo;
    private String acctRemark;
    private Date lstIbIl;
    private String lstTime;
    private Date selfMngIl;
    private String ibfGb;
    private BigDecimal lmtMaxAmt;
    private String pbookNo;
    private String ebUseGb;
    private String netClsPossYn;
    private String netPayPossYn;
    private String bankDvCd;
    private String trfPsbkReprtYn;
    private String signFileNm;
    private String biPrdCd;
    private String biMsrmCtgr;
    private String biAcctPrpt;
    private String prcpWithMethCd;
    private String intWithMethCd;
    private String prcpAcctNo;
    private String intAcctNo;
    private BigDecimal prcpTmplCd;
    private BigDecimal intTmplCd;
    private String certNo;
    private String sendAddrDv;
    private String comBit;
    private BigDecimal amt1;
    private BigDecimal amt2;
    private BigDecimal amt3;
    private BigDecimal amt4;
    private BigDecimal amt5;
    private BigDecimal amt6;
    private BigDecimal amt7;
    private BigDecimal amt8;
    private BigDecimal amt9;
    private BigDecimal amt10;
    private String cd1;
    private String cd2;
    private String cd3;
    private String cd4;
    private String cd5;
    private String cd6;
    private String cd7;
    private String cd8;
    private String cd9;
    private String cd10;
    private BigDecimal rt1;
    private BigDecimal rt2;
    private BigDecimal rt3;
    private BigDecimal rt4;
    private BigDecimal rt5;
    private Date dt1;
    private Date dt2;
    private Date dt3;
    private Date dt4;
    private Date dt5;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String pwdLossGb;
} 
