package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "ADST_DPB_BASE") 
@Data 
public class ADST_DPB_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private int lonIntYcInt; 
private int dptNegoRt; 
private int bfTmInt; 
private int stopAmt; 
private int lmtBlkAmt; 
private int lstTrxNo; 
private Date updDt; 
private String lonYdCd; 
private String pwd; 
private int prepayDay; 
private String regEmpNo; 
private String lonBsCd; 
private Date lonIntCalIl; 
private Date lonTermIl; 
private String lstTime; 
private int intPayCnt; 
private int rt1; 
private int rt3; 
private int rt2; 
private int rt5; 
private int rt4; 
private int openExptAmt; 
private Date dptIntCalIl; 
private int clsCnt; 
private String intPayGb; 
private int prcpOverDueIntRt; 
private Date lonFstYcIl; 
private String acctCcy; 
private String intCalMethCd; 
private String dptBbsCd; 
private Date rollOverIl; 
private int dptBasicRt; 
private int bfTmTax; 
private Date lonIntRcvIl; 
private Date dptManIl; 
private String intRtDv; 
private Date opnIl; 
private int maxJan; 
private int bsJan; 
private String intCalGb; 
private int clsAmt; 
private String cd10; 
private int taxRt; 
private int ftpRt; 
private String dptPlCd; 
private Date isIl; 
private Date ccNgIl; 
private int amt10; 
private int depCnt; 
private String taxCd; 
private int lonPrcpYcInt; 
private String updEmpNo; 
private Date ysdIl; 
private int amt8; 
private int amt9; 
private int amt6; 
private int dueAmt; 
private int amt7; 
private int amt4; 
private int intTermGb; 
private int amt5; 
private int amt2; 
private int amt3; 
private String baseCcy; 
private int openAmt; 
private int amt1; 
private Date janCertiIl; 
private String randSalt; 
private Date selfMngIl; 
private String dptTypeGb; 
private Date dt1; 
private String reserved1; 
private Date dt3; 
private Date dt2; 
private String dptBsCd; 
private Date dt5; 
private int curJan; 
private Date dt4; 
private Date noticeIl; 
private String acctType; 
private String empPayAcctPwd; 
private Date jagumIl; 
private int fstJan; 
private String lonBbsCd; 
private int collatAmt; 
private int lstDrTrxNo; 
private Date lonManIl; 
private String acctNo; 
private int intOverDueIntRt; 
private String lonRtCd; 
private int mTerm; 
private int colLonInt; 
private Date regDt; 
private String ftpRtGb; 
private Date lstIbIl; 
private String lonPlCd; 
private int dTerm; 
private int lonSngAmt; 
private String cd2; 
private String cd1; 
private String cd4; 
private String cd3; 
private String cd6; 
private String cd5; 
private String cd8; 
private String cd7; 
private int lonRt; 
private String cd9; 
private String daysCalcMethCd; 
private String updTm; 
private String regTm; 
} 
