package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "adstLnbBase")
@Data
public class ADST_LNB_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String ikisSts;
    private String bkGb;
    private String cixNo;
    private String buseoNo;
    private String comId;
    private String comNm;
    private Date openIl;
    private Date totExpIl;
    private Date realExpIl;
    private Date fstExpIl;
    private String lonCcy;
    private BigDecimal fstLonAmt;
    private BigDecimal lonJan;
    private String repayGb;
    private String schGb;
    private String termGb;
    private String accrualGb;
    private String actGb;
    private BigDecimal guchTerm;
    private BigDecimal repayTerm;
    private BigDecimal repayGap;
    private String repayGapGb;
    private BigDecimal graceDays;
    private BigDecimal repayCnt;
    private Date fstRepayIl;
    private Date lstRepayIl;
    private Date nxRepayIl;
    private Date lstIsuIl;
    private Date lstIibIl;
    private Date nxIsuIl;
    private Date nxRollIl;
    private Date lstBillIl;
    private Date nxBillIl;
    private BigDecimal lstRt;
    private BigDecimal misuAmt;
    private BigDecimal misuSeq;
    private BigDecimal mkjAmt;
    private BigDecimal mkjSeq;
    private BigDecimal repayAdjSeq;
    private BigDecimal repayNxSeq;
    private BigDecimal intAdjSeq;
    private BigDecimal intNxSeq;
    private String prnYcGb;
    private Date prnYcIl;
    private String intYcGb;
    private Date intYcIl;
    private BigDecimal ycGun;
    private BigDecimal timesPastDueCnt;
    private BigDecimal regPayAmt;
    private String nonEqGb;
    private BigDecimal nonEqAmt;
    private String rateCcy;
    private String fixFltGb;
    private String spreadGb;
    private BigDecimal spreadRt;
    private String rateChgYn;
    private BigDecimal rollGap;
    private String rollGapGb;
    private String lateChgYn;
    private BigDecimal lateChgRt;
    private BigDecimal pastDueRt;
    private BigDecimal accrualRt;
    private String capRtYn;
    private BigDecimal capRtLife;
    private BigDecimal capRtPrd;
    private String floorRtYn;
    private BigDecimal floorRtLife;
    private BigDecimal floorRtPrd;
    private String advArrGb;
    private String singleBothType;
    private String accrType;
    private String bsnsDayRule;
    private BigDecimal intGap;
    private String intGapGb;
    private String intAdjYn;
    private BigDecimal allInYield;
    private String hdSngNo;
    private String feeYn;
    private BigDecimal appliFee;
    private BigDecimal origiFee;
    private BigDecimal renewFee;
    private BigDecimal brokaFee;
    private BigDecimal otherFee;
    private String sndDocNo;
    private String thrRcvDepoCcy;
    private String thrRcvDepoBic;
    private String evidNo;
    private String evidCcy;
    private BigDecimal evidAmt;
    private BigDecimal usdCvtAmt;
    private BigDecimal bbsCvtAmt;
    private String autoDebitYn;
    private BigDecimal lossAmt;
    private String restructuringYn;
    private Date fstIbIl;
    private Date lstDealIl;
    private Date lstIbIl;
    private String opNo;
    private String ownerNo;
    private String rmpbNo;
    private String ibfGb;
    private String blNo;
    private Date lgOpenIl;
    private BigDecimal nxtRt;
    private String nxtSchYn;
    private String newSchYn;
    private Date msgLstIsuIl;
    private String agrRefNo;
    private BigDecimal agrSeqNo;
    private String longShortType;
    private String flatSliding;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String partialYn;
    private Date partialExpiDt;
    private BigDecimal partialAmt;
    private BigDecimal partialJan;
    private String lnPrpsCd;
} 
