package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "adstLnbItm")
@Data
public class ADST_LNB_ITMInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private BigDecimal hisNo;
    private String sts;
    private String trCd;
    private String itmCd;
    private Date bfTotExpIl;
    private Date afTotExpIl;
    private Date bfRealExpIl;
    private Date afRealExpIl;
    private String bfRepayGb;
    private String afRepayGb;
    private String bfSchGb;
    private String afSchGb;
    private String bfAccrualGb;
    private String afAccrualGb;
    private String bfActGb;
    private String afActGb;
    private BigDecimal bfGraceDays;
    private BigDecimal afGraceDays;
    private BigDecimal bfTimesPast;
    private BigDecimal afTimesPast;
    private String bfIntAdjYn;
    private String afIntAdjYn;
    private String bfEvidNo;
    private String afEvidNo;
    private String bfEvidCcy;
    private String afEvidCcy;
    private BigDecimal bfEvidAmt;
    private BigDecimal afEvidAmt;
    private String bfAutoDebitYn;
    private String afAutoDebitYn;
    private String bfLastChgYn;
    private String afLastChgYn;
    private BigDecimal bfLastChgRt;
    private BigDecimal afLastChgRt;
    private BigDecimal bfPastDueRt;
    private BigDecimal afPastDueRt;
    private BigDecimal bfAccrualRt;
    private BigDecimal afAccrualRt;
    private BigDecimal bfRepayGap;
    private BigDecimal afRepayGap;
    private String bfRepayGapGb;
    private String afRepayGapGb;
    private BigDecimal bfRepayTerm;
    private BigDecimal afRepayTerm;
    private BigDecimal bfRepayAdjSeq;
    private BigDecimal afRepayAdjSeq;
    private String bfPrnYcGb;
    private String afPrnYcGb;
    private Date bfPrnYcIl;
    private Date afPrnYcIl;
    private BigDecimal bfGuchTerm;
    private BigDecimal afGuchTerm;
    private BigDecimal bfIntGap;
    private BigDecimal afIntGap;
    private String bfIntGapGb;
    private String afIntGapGb;
    private BigDecimal bfIntAdjSeq;
    private BigDecimal afIntAdjSeq;
    private String bfIntYcGb;
    private String afIntYcGb;
    private Date bfIntYcIl;
    private Date afIntYcIl;
    private String bfAdvArrGb;
    private String afAdvArrGb;
    private String bfSingleBothType;
    private String afSingleBothType;
    private String bfAccrType;
    private String afAccrType;
    private String bfBsnsDayRule;
    private String afBsnsDayRule;
    private BigDecimal bfRollGap;
    private BigDecimal afRollGap;
    private String bfRollGapGb;
    private String afRollGapGb;
    private String bfFixFltGb;
    private String afFixFltGb;
    private String bfSpreadGb;
    private String afSpreadGb;
    private BigDecimal bfSpreadRt;
    private BigDecimal afSpreadRt;
    private BigDecimal bfLstRt;
    private BigDecimal afLstRt;
    private String bfRateChgYn;
    private String afRateChgYn;
    private Date fstIbIl;
    private Date lstAcIl;
    private Date lstIbIl;
    private Date bfNxRollIl;
    private Date afNxRollIl;
    private BigDecimal bfNxtRt;
    private BigDecimal afNxtRt;
    private String bfNxtSchYn;
    private String afNxtSchYn;
    private String bfNewSchYn;
    private String afNewSchYn;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
