package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afexRihRefund")
@Data
public class AFEX_RIH_REFUNDInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private BigDecimal seqNo;
    private String sts;
    private String rtCd;
    private String moneyCd;
    private String rcvGb;
    private String rcvBr;
    private String cixNo;
    private String ccy;
    private BigDecimal famt;
    private BigDecimal orgFamt;
    private String theirRefNo;
    private String chGb;
    private BigDecimal chAmt;
    private String mjGb;
    private BigDecimal feeCnt;
    private String feeMsg;
    private String inmsgGb;
    private String inMsg;
    private String creditCur;
    private BigDecimal creditAmt;
    private Date creditIl;
    private String applNm;
    private String applAddr1;
    private String applAddr2;
    private String applAddr3;
    private String apliAcno;
    private String jgDepoCd;
    private String jgDepoNm;
    private String jgBkcd;
    private String jgBkAbano;
    private String jgBknm;
    private String jgBkAddr1;
    private String jgBkAddr2;
    private String jgBkAddr3;
    private String rcvNm;
    private String rcvAddr1;
    private String rcvAddr2;
    private String rcvAddr3;
    private String rcvAcctNo;
    private String depoCode;
    private String depoName1;
    private String sbankBkcd;
    private String sbankBknm;
    private String sbankAddr1;
    private String sbankAddr2;
    private String sbankAddr3;
    private String cbankBkcd;
    private String cbankBknm;
    private String cbankAddr1;
    private String cbankAddr2;
    private String cbankAddr3;
    private Date valueDate;
    private String feeCur;
    private BigDecimal feeAmt;
    private String info70Name1;
    private String info70Name2;
    private String info70Name3;
    private String info70Name4;
    private String infoName1;
    private String infoName2;
    private String infoName3;
    private String infoName4;
    private String infoName5;
    private String infoName6;
    private String intBkcd;
    private String intBknm;
    private String intBkAddr1;
    private String intBkAddr2;
    private String intBkAddr3;
    private String intBkAcct;
    private String jgBkAcct;
    private String procType;
    private String imad;
    private String omad;
    private Date requestIl;
    private BigDecimal requestHis;
    private Date amendIl;
    private BigDecimal amendHis;
    private String outmsgGb;
    private String refundRecvMttype;
    private String refundRecvMsg;
    private Date refundRecvIl;
    private String quesSendMttype;
    private String quesSendMsg;
    private Date quesSendIl;
    private String cnfmRecvMttype;
    private String cnfmRecvMsg;
    private Date cnfmRecvIl;
    private String rfndSendMttype;
    private String rfndSendMsg;
    private Date rfndSendIl;
    private BigDecimal refundAmt;
    private BigDecimal amdAmt;
    private BigDecimal amdComm;
    private BigDecimal amdFee;
    private String refundTheirRef;
    private String refundRemark1;
    private String refundRemark2;
    private String refundRemark3;
    private String refundRemark4;
    private String refundRemark5;
    private String refundRemark6;
    private String refundRemark7;
    private String refundRemark8;
    private String mngBr;
    private String operId;
    private String mngrId;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
