package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "AFEX_ADH_BASE")
@Data
public class AFEX_ADH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String BENE_CD;
    private Date GYOBU_IL;
    private String EDI_CHURI;
    private String BUSEO_NO;
    private String HS_CD;
    private String MNG_NO;
    private String DRAW_BKNM3;
    private String TRAN_INPUT;
    private String REIM_BKCD;
    private Date UPD_DT;
    private String PRICE_COND;
    private String DRAW_BKNM2;
    private String DRAW_BKCD;
    private String DRAW_BKNM1;
    private String NOR_URG;
    private String USANCE_DAY;
    private Date EXP_IL;
    private int TOL_LESS;
    private int BR_CHARGE;
    private int CHARGE_AMT;
    private int TOT_SEQ;
    private String THRU_BKCD;
    private String REG_EMP_NO;
    private String OPEN_CCY;
    private String LOCAL_CD;
    private Date CHARGE_IL;
    private String LST_TIME;
    private String THRU_BKNM1;
    private String THRU_BKNM2;
    private String EDI_GB;
    private String THRU_BKNM3;
    private Date CNFR_FR_IL;
    private String SIGHT_GB;
    private String FIRST_GB;
    private String ADV_NO;
    private String TRAILER;
    private String SEND_GB;
    private String OUR_CUST_GB;
    private String IBGM_MD;
    private String MT701_FNM1;
    private String MT701_FNM2;
    private String MT701_FNM3;
    private String MT701_FNM4;
    private String EDI_SUIN;
    private int SEQ_NO;
    private String TONG_PRINT;
    private int CNFR_RT;
    private String MT730_DOC_ID;
    private int TOL_MORE;
    private String TX_KEY;
    private String MSG_GB;
    private String SWIFT_MRN;
    private String FAX_GB;
    private String CHARGE_CCY;
    private String HS_NM;
    private String EDI_ID;
    private String FAX_NO;
    private Date MAKE_IL;
    private Date LST_EXP_IL;
    private String APPL_NM4;
    private String APPL_NM3;
    private String CNFM_BIC;
    private String MT710_SEND;
    private String APPL_NM2;
    private String APPL_NM1;
    private String ADV_THRU_GB;
    private Date TRAN_IL;
    private String UPD_EMP_NO;
    private String COND_STS;
    private String REIM_BKNM3;
    private String REIM_BKNM2;
    private String REIM_BKNM1;
    private String AUTH_GB;
    private String HS_REAL;
    private int OPEN_AMT;
    private Date LST_IL;
    private String MT700_FNM;
    private String CTRY_NM;
    private String OP_NO;
    private Date SHIP_IL;
    private String CHARGE_MD;
    private String MT730_SEND;
    private String MSG_TYPE;
    private int PRT_CNT;
    private String SKBDN_YN;
    private Date OPEN_IL;
    private String OPEN_BKCD;
    private String BR_NM;
    private String LC_NO;
    private String CTRY_CD;
    private int MT701_CNT;
    private String EDI_SEND;
    private String RELAY;
    private String MT710_DOC_ID;
    private String BR_NO;
    private Date CNFR_TO_IL;
    private String RE_ISSUE;
    private String GYOBU_GB;
    private String BENE_NM2;
    private Date REG_DT;
    private String BENE_NM3;
    private String BENE_NM1;
    private int AMD_CNT;
    private String CIX_NO;
    private Date FIRST_IL;
    private String CHARGE_GB;
    private String OPEN_BKNM2;
    private String OPEN_BKNM1;
    private String OPEN_BKNM3;
    private String CNFM_NM1;
    private String CNFM_NM3;
    private int BAL_AMT;
    private String CNFM_NM2;
    private String CONFIRM_GB;
    private String UPD_TM;
    private String BENE_NM4;
    private String BOK_SEND;
    private String REG_TM;
} 
