package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afexIpbBase")
@Data
public class AFEX_IPB_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String ikisSts;
    private String bkGb;
    private String cixNo;
    private String buseoNo;
    private String ipCcy;
    private BigDecimal ipJan;
    private BigDecimal gtJan;
    private BigDecimal lgsJan;
    private BigDecimal lguJan;
    private BigDecimal bldJan;
    private BigDecimal insJan;
    private BigDecimal bojJan;
    private BigDecimal bojJan1;
    private BigDecimal bojJan2;
    private BigDecimal bojBjan;
    private BigDecimal bojBjan1;
    private BigDecimal bojBjan2;
    private BigDecimal corJan;
    private BigDecimal djbBjan;
    private BigDecimal bldSeq;
    private BigDecimal amdSeq;
    private BigDecimal lgmSeq;
    private BigDecimal ikisSeq;
    private BigDecimal ikisHisNo;
    private BigDecimal corSeq;
    private BigDecimal djbSeq;
    private BigDecimal bojSeq;
    private BigDecimal jajSeq;
    private BigDecimal itmSeq;
    private Date openIl;
    private Date gisIl;
    private Date lstIl;
    private Date lstIbIl;
    private String openCcy;
    private BigDecimal openAmt;
    private String ipCd;
    private String bunGb;
    private String miltGb;
    private Date expIl;
    private BigDecimal bojJukYul;
    private String priceCd;
    private String hsCd;
    private String hsNm;
    private String origCtry;
    private String sdCtry;
    private String termGb;
    private BigDecimal term;
    private String hdSngNo;
    private String canAccGb;
    private String poNo;
    private String unsongGb;
    private String tcFrtGb;
    private BigDecimal tcFrt;
    private Date tcLisuIl;
    private BigDecimal tcDsamt;
    private BigDecimal tcHrt;
    private String tcTermGb;
    private String tcRcvGb;
    private String slCd;
    private String slYoCd;
    private String setBkcd;
    private String acptBkcd;
    private String confBkcd;
    private String reOpGb;
    private String reopBkcd;
    private BigDecimal reFrtYul;
    private String reReGb;
    private String reReGb1;
    private String opNo;
    private String ownerNo;
    private String pbrmNo;
    private BigDecimal corFrt;
    private BigDecimal sprdFrt;
    private String lcNo;
    private String amtMore;
    private String amtLess;
    private String revolveGb;
    private String partshipGb;
    private String gyom;
    private String comId;
    private String ibfGb;
    private BigDecimal tcMisuCnt;
    private BigDecimal tcFrt2;
    private BigDecimal tcDsamt2;
    private String beniCtry;
    private String boseGb;
    private String beniNm;
    private BigDecimal tolJan;
    private BigDecimal tolUse;
    private String skbdnYn;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
