package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_IPH_BASE") 
@Data 
public class AFEX_IPH_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private String tranSeqno; 
private String bankGb; 
private String invoInfo; 
private String transGb; 
private String befBadd1; 
private String befBadd2; 
private String sts; 
private Date updDt; 
private Date expIl; 
private String applAddr1; 
private String befReim; 
private String applAddr2; 
private String reimBic; 
private String sendJumgb; 
private String spcGb; 
private String applAddr3; 
private String befBadd3; 
private String regEmpNo; 
private String openCcy; 
private String amdLno; 
private int ediSeqNo; 
private String negoBic; 
private String ediSfnm; 
private String ediCust; 
private String partGb; 
private String ediGb; 
private String applCd; 
private String mt700Nm; 
private String mt701Nm1; 
private String mt701Nm2; 
private String blGb; 
private String advNm; 
private int ncuOpenAmt; 
private String cbsGb; 
private String packInfo; 
private String ediRfnm; 
private String orgnNm2; 
private String orgnNm1; 
private String priceCd; 
private String raGb; 
private String usanTerm; 
private String intGb; 
private String tenorGb; 
private String advBic; 
private String expPlace; 
private String discPort; 
private String packCnt; 
private String ediRcv; 
private String fromPort; 
private String tranGb; 
private String beneNm; 
private String thrBic; 
private String applRule2; 
private String presPrd; 
private String raliboGb; 
private String lastCcy; 
private String amdLseq; 
private String cableGb; 
private String openGb; 
private String insurGb; 
private String cnfmBic; 
private String termGb; 
private String toPort; 
private Date ediSndIl; 
private String usanGb; 
private String befBnm; 
private Date tranIl; 
private String termType; 
private String updEmpNo; 
private String commodity; 
private String invoCnt; 
private String draweeBic; 
private String ncuLastCcy; 
private String cnfmGb; 
private String applRule; 
private int openAmt; 
private String loadPort; 
private String applNm; 
private String befAdv; 
private String draftRate; 
private String ediJumNo; 
private Date shipIl; 
private String amtMore; 
private String skbdnYn; 
private Date openIl; 
private String beneAddr1; 
private String reimNm; 
private String adGb; 
private int lastAmt; 
private String beneAddr3; 
private String beneAddr2; 
private String negoGb; 
private String ncuOpenCcy; 
private String ediSend; 
private String operNo; 
private Date ediRcvIl; 
private String refNo; 
private String mt7nnGb; 
private String draweeNm; 
private Date regDt; 
private int ncuLastAmt; 
private String mngInfo; 
private String mt740Nm; 
private String insurCd; 
private String thrNm1; 
private String freightGb; 
private String thrNm2; 
private String priceNm; 
private String reimDepo; 
private String thrNm3; 
private String thrNm4; 
private String negoNm; 
private String chargeGb; 
private String amtLess; 
private String theirRef; 
private String cnfmNm; 
private int raRate; 
private String updTm; 
private String ttreimGb; 
private String openWay; 
private String regTm; 
} 
