package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "AFEX_ADH_AMEND")
@Data
public class AFEX_ADH_AMENDInfo implements Serializable {
    @Id
    @GeneratedValue
    private Date makeIl;
    private int seqNo;
    private int lstHisNo;
    private String advNo;
    private String sendGb;
    private String lcNo;
    private Date openIl;
    private int amdCnt;
    private String openBkcd;
    private String openBknm1;
    private String openBknm2;
    private String openBknm3;
    private String beneCd;
    private String beneNm1;
    private String beneNm2;
    private String beneNm3;
    private String amdGb;
    private String gyobuGb;
    private Date gyobuIl;
    private String amtGb;
    private String amdCcy;
    private int amdAmt;
    private String afCcy;
    private int afAmt;
    private Date expIl;
    private Date shipIl;
    private String authGb;
    private String ediChuri;
    private String ediSend;
    private String faxAdv;
    private String faxSend;
    private String tail;
    private String norUrg;
    private String swiftMrn;
    private String mngNo;
    private String opNo;
    private int totSeq;
    private Date lstIl;
    private String mt707Fnm;
    private String relay;
    private String lstTime;
    private String txKey;
    private String msgType;
    private String ediId;
    private String condSts;
    private String ediSuin;
    private String bokSend;
    private String tongPrint;
    private String brNo;
    private String brNm;
    private int brCharge;
    private int chargeAmt;
    private String chargeGb;
    private String cixNo;
    private String buseoNo;
    private String ibgmMd;
    private String chargeMd;
    private Date chargeIl;
    private String mt707Fnm1;
    private int prtCnt;
    private String reIssue;
    private String mt707Fnm2;
    private String mt707Fnm3;
    private String mt707Fnm4;
    private int mt707Cnt;
    private String mt730Send;
    private String mt730DocId;
    private Date firstIl;
    private String mt710Send;
    private String mt710DocId;
    private String chargeCcy;
    private String ourCustGb;
    private String beneNm4;
    private String mt707DocId;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String applNm1;
    private String applNm2;
    private String applNm3;
    private String applNm4;
    private String drawBkcd;
    private String drawBknm1;
    private String drawBknm2;
    private String drawBknm3;
    private String reimBkcd;
    private String reimBknm1;
    private String reimBknm2;
    private String reimBknm3;
    private String advThruGb;
    private String thruBkcd;
    private String thruBknm1;
    private String thruBknm2;
    private String thruBknm3;
    private String confirmGb;
    private Date cnfrFrIl;
    private Date cnfrToIl;
    private int cnfrRt;
    private String cnfmBic;
    private String cnfmNm1;
    private String cnfmNm2;
    private String cnfmNm3;
    private String mt708Fnm1;
    private String mt708Fnm2;
    private String mt708Fnm3;
    private String mt708Fnm4;
    private int mt708Cnt;
} 
