package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_XPB_HIS") 
@Data 
public class AFEX_XPB_HISInfo implements Serializable { 
@Id 
@GeneratedValue 
private int edisnd1SeqNo; 
private String trCd; 
private String hijaGb; 
private String mngNo; 
private String updEmpNo; 
private String hcGb; 
private int gitaAmt; 
private String cdSngNo; 
private String plCd; 
private String sts; 
private int beTerm; 
private int trBamt; 
private Date updDt; 
private int beHrt; 
private int trFamt; 
private int edisnd4SeqNo; 
private String ibTime; 
private int edisnd2SeqNo; 
private int edisnd3SeqNo; 
private int edisnd5SeqNo; 
private String ijGb; 
private Date canIl; 
private int ftpSilSeq; 
private String regEmpNo; 
private String opNo; 
private String edisndDoc5Nm; 
private Date gisIl; 
private int sdHisNo; 
private Date beYdcIl; 
private int beFtpRt; 
private int hisNo; 
private String ydGuja; 
private int afJan; 
private Date ibIl; 
private int suspayHisNo1; 
private String edircvDocNm; 
private int suspayHisNo2; 
private int actpayHisNo1; 
private Date baeseoIl; 
private Date beShIl; 
private String bePbrmNo; 
private String trCcy; 
private int ydSeq; 
private String edisndDoc4Nm; 
private int beIkisIj; 
private Date edircvIl; 
private int caSeq; 
private String sdBr; 
private int cdSilSeq; 
private Date beLisuIl; 
private Date acIl; 
private Date beBudoIl; 
private int edircvSeqNo; 
private String refNo; 
private String ftpSngNo; 
private String edisndDoc1Nm; 
private String jichmGb; 
private Date regDt; 
private String ibjiMd; 
private String bijaGb; 
private String edisndDoc3Nm; 
private int beHRt; 
private int beIkisHis; 
private String jichGb; 
private int bokSeq; 
private String cixNo; 
private int beHterm; 
private String feeMd; 
private String trBr; 
private String trGb; 
private String edisndDoc2Nm; 
private String beHdSngNo; 
private Date beYmanIl; 
private String updTm; 
private int crBamt; 
private String regTm; 
} 
