package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_IPH_AMD") 
@Data 
public class AFEX_IPH_AMDInfo implements Serializable { 
@Id 
@GeneratedValue 
private String amdNo; 
private Date ediSndIl; 
private String purposeCd; 
private int ncuBefoAmt; 
private Date tranIl; 
private String termType; 
private String updEmpNo; 
private int decAmt; 
private String bankGb; 
private String transGb; 
private String partShip; 
private String draweeBic; 
private String befoCcy; 
private String applRule; 
private String cnfmGb; 
private String sts; 
private Date updDt; 
private String amdCcy; 
private String loadPort; 
private String applNm; 
private String draftRate; 
private Date expIl; 
private String mt747Nm; 
private String applAddr1; 
private String reimBic; 
private String sendJumgb; 
private String applAddr2; 
private String applAddr3; 
private String regEmpNo; 
private int befoAmt; 
private String ediJumNo; 
private int ediSeqNo; 
private int hisNo; 
private String ncuAmdCcy; 
private Date shipIl; 
private String ediSfnm; 
private String negoBic; 
private String ediCust; 
private String amtMore; 
private String ediGb; 
private String applCd; 
private String thrNm; 
private Date openIl; 
private String advNm; 
private int incAmt; 
private String cbsGb; 
private int ncuDecAmt; 
private String beneAddr1; 
private String reimNm; 
private String ediRfnm; 
private int amdAmt; 
private String orgnNm2; 
private String beneAddr3; 
private String orgnNm1; 
private String cancelCd; 
private String beneAddr2; 
private String raGb; 
private String negoGb; 
private String usanTerm; 
private String operNo; 
private String ediSend; 
private String tranShip; 
private String advBic; 
private Date ediRcvIl; 
private String discPort; 
private String refNo; 
private String mt707Nm; 
private String ediRcv; 
private String amdSeq; 
private String fromPort; 
private String draweeNm; 
private Date regDt; 
private String beneNm; 
private Date amdIl; 
private String mngInfo; 
private String thrBic; 
private int ncuIncAmt; 
private String applRule2; 
private String priceNm; 
private String presPrd; 
private String thrNm2; 
private String thrNm3; 
private String thrNm4; 
private String chargeGb; 
private String amtLess; 
private String ncuBefoCcy; 
private String theirRef; 
private int ncuAmdAmt; 
private String cnfmNm; 
private String updTm; 
private String cnfmBic; 
private String ttreimGb; 
private String toPort; 
private String regTm; 
private String termGb; 
} 
