package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "AFEX_IPH_BASE")
@Data
public class AFEX_IPH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private Date tranIl;
    private String tranSeqno;
    private String advBic;
    private String advNm;
    private Date openIl;
    private String thrNm1;
    private String thrNm2;
    private String cnfmGb;
    private String transGb;
    private String applCd;
    private String applNm;
    private String applAddr1;
    private String applAddr2;
    private String applAddr3;
    private String beneNm;
    private String beneAddr1;
    private String beneAddr2;
    private String beneAddr3;
    private String openCcy;
    private int openAmt;
    private Date expIl;
    private String expPlace;
    private String openGb;
    private String openWay;
    private String tenorGb;
    private String usanGb;
    private String usanTerm;
    private String termGb;
    private String termType;
    private String draftRate;
    private String intGb;
    private String ttreimGb;
    private String raGb;
    private String draweeBic;
    private String draweeNm;
    private String reimBic;
    private String reimNm;
    private String blGb;
    private String freightGb;
    private String invoCnt;
    private String invoInfo;
    private String packCnt;
    private String packInfo;
    private String insurCd;
    private String insurGb;
    private String fromPort;
    private String toPort;
    private Date shipIl;
    private String partGb;
    private String tranGb;
    private String chargeGb;
    private String adGb;
    private String negoGb;
    private String negoBic;
    private String negoNm;
    private String presPrd;
    private String orgnNm1;
    private String orgnNm2;
    private String priceCd;
    private String priceNm;
    private String amtMore;
    private String amtLess;
    private String commodity;
    private String reimDepo;
    private String amdLseq;
    private String amdLno;
    private String lastCcy;
    private int lastAmt;
    private String ediGb;
    private String ediCust;
    private String ediSend;
    private Date ediSndIl;
    private String ediJumNo;
    private int ediSeqNo;
    private String ediSfnm;
    private String ediRcv;
    private Date ediRcvIl;
    private String ediRfnm;
    private String sts;
    private String operNo;
    private String mt700Nm;
    private String mt701Nm1;
    private String mt701Nm2;
    private String mt740Nm;
    private String befAdv;
    private String befReim;
    private String befBnm;
    private String befBadd1;
    private String befBadd2;
    private String befBadd3;
    private String sendJumgb;
    private String bankGb;
    private String mt7nnGb;
    private String ncuOpenCcy;
    private int ncuOpenAmt;
    private String ncuLastCcy;
    private int ncuLastAmt;
    private String cbsGb;
    private String theirRef;
    private String cableGb;
    private String spcGb;
    private String mngInfo;
    private String raliboGb;
    private int raRate;
    private String applRule;
    private String applRule2;
    private String loadPort;
    private String discPort;
    private String thrNm3;
    private String thrNm4;
    private String skbdnYn;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String cnfmBic;
    private String cnfmNm;
    private String thrBic;
} 
