package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_ADH_BASE") 
@Data 
public class AFEX_ADH_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private String beneCd; 
private Date gyobuIl; 
private String ediChuri; 
private String buseoNo; 
private String hsCd; 
private String mngNo; 
private String drawBknm3; 
private String tranInput; 
private String reimBkcd; 
private Date updDt; 
private String priceCond; 
private String drawBknm2; 
private String drawBkcd; 
private String drawBknm1; 
private String norUrg; 
private String usanceDay; 
private Date expIl; 
private int tolLess; 
private int brCharge; 
private int chargeAmt; 
private int totSeq; 
private String thruBkcd; 
private String regEmpNo; 
private String openCcy; 
private String localCd; 
private Date chargeIl; 
private String lstTime; 
private String thruBknm1; 
private String thruBknm2; 
private String ediGb; 
private String thruBknm3; 
private Date cnfrFrIl; 
private String sightGb; 
private String firstGb; 
private String advNo; 
private String trailer; 
private String sendGb; 
private String ourCustGb; 
private String ibgmMd; 
private String mt701Fnm1; 
private String mt701Fnm2; 
private String mt701Fnm3; 
private String mt701Fnm4; 
private String ediSuin; 
private int seqNo; 
private String tongPrint; 
private int cnfrRt; 
private String mt730DocId; 
private int tolMore; 
private String txKey; 
private String msgGb; 
private String swiftMrn; 
private String faxGb; 
private String chargeCcy; 
private String hsNm; 
private String ediId; 
private String faxNo; 
private Date makeIl; 
private Date lstExpIl; 
private String applNm4; 
private String applNm3; 
private String cnfmBic; 
private String mt710Send; 
private String applNm2; 
private String applNm1; 
private String advThruGb; 
private Date tranIl; 
private String updEmpNo; 
private String condSts; 
private String reimBknm3; 
private String reimBknm2; 
private String reimBknm1; 
private String authGb; 
private String hsReal; 
private int openAmt; 
private Date lstIl; 
private String mt700Fnm; 
private String ctryNm; 
private String opNo; 
private Date shipIl; 
private String chargeMd; 
private String mt730Send; 
private String msgType; 
private int prtCnt; 
private String skbdnYn; 
private Date openIl; 
private String openBkcd; 
private String brNm; 
private String lcNo; 
private String ctryCd; 
private int mt701Cnt; 
private String ediSend; 
private String relay; 
private String mt710DocId; 
private String brNo; 
private Date cnfrToIl; 
private String reIssue; 
private String gyobuGb; 
private String beneNm2; 
private Date regDt; 
private String beneNm3; 
private String beneNm1; 
private int amdCnt; 
private String cixNo; 
private Date firstIl; 
private String chargeGb; 
private String openBknm2; 
private String openBknm1; 
private String openBknm3; 
private String cnfmNm1; 
private String cnfmNm3; 
private int balAmt; 
private String cnfmNm2; 
private String confirmGb; 
private String updTm; 
private String beneNm4; 
private String bokSend; 
private String regTm; 
} 
