package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_RIH_REFUND") 
@Data 
public class AFEX_RIH_REFUNDInfo implements Serializable { 
@Id 
@GeneratedValue 
private Date refundRecvIl; 
private String sts; 
private Date updDt; 
private String applAddr1; 
private String applAddr2; 
private String applAddr3; 
private String rfndSendMttype; 
private String regEmpNo; 
private String jgBkcd; 
private String refundRemark7; 
private String refundRemark8; 
private String chGb; 
private String cbankAddr2; 
private String cbankAddr1; 
private String jgDepoNm; 
private String cbankAddr3; 
private String cbankBkcd; 
private String operId; 
private String jgBkAcct; 
private String intBknm; 
private int creditAmt; 
private String refundRemark3; 
private String refundRemark4; 
private String refundRemark5; 
private String refundRemark6; 
private String refundRemark1; 
private String rcvNm; 
private String refundRemark2; 
private int amdAmt; 
private String info70Name4; 
private String info70Name3; 
private String rcvBr; 
private String inMsg; 
private int requestHis; 
private String info70Name2; 
private int seqNo; 
private String info70Name1; 
private String refundRecvMttype; 
private int feeCnt; 
private int refundAmt; 
private String jgBkAbano; 
private Date creditIl; 
private String sbankAddr1; 
private String sbankAddr2; 
private String imad; 
private String sbankAddr3; 
private String feeCur; 
private String quesSendMttype; 
private String cnfmRecvMsg; 
private int amendHis; 
private String depoCode; 
private String intBkAddr3; 
private String intBkAddr1; 
private String intBkAddr2; 
private String creditCur; 
private int famt; 
private int orgFamt; 
private int amdComm; 
private String jgBknm; 
private String sbankBkcd; 
private String mngrId; 
private String updEmpNo; 
private String jgDepoCd; 
private String cbankBknm; 
private String refundRecvMsg; 
private String intBkAcct; 
private String applNm; 
private String jgBkAddr1; 
private String jgBkAddr2; 
private String jgBkAddr3; 
private String outmsgGb; 
private String feeMsg; 
private String depoName1; 
private String omad; 
private String quesSendMsg; 
private String inmsgGb; 
private Date valueDate; 
private Date quesSendIl; 
private String cnfmRecvMttype; 
private String moneyCd; 
private int chAmt; 
private Date rfndSendIl; 
private String mngBr; 
private String procType; 
private Date amendIl; 
private String rcvGb; 
private Date requestIl; 
private String apliAcno; 
private String rtCd; 
private String infoName6; 
private String infoName5; 
private String intBkcd; 
private String refNo; 
private String infoName4; 
private String infoName3; 
private String infoName2; 
private String infoName1; 
private String rcvAcctNo; 
private String refundTheirRef; 
private String mjGb; 
private Date regDt; 
private String rcvAddr1; 
private String sbankBknm; 
private int feeAmt; 
private String theirRefNo; 
private String rcvAddr2; 
private String rcvAddr3; 
private String rfndSendMsg; 
private String cixNo; 
private Date cnfmRecvIl; 
private String ccy; 
private int amdFee; 
private String updTm; 
private String regTm; 
} 
