package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "afexIphAmd")
@Data
public class AFEX_IPH_AMDInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String amdSeq;
    private String amdNo;
    private Date tranIl;
    private Date amdIl;
    private String sts;
    private String advBic;
    private String advNm;
    private Date openIl;
    private String theirRef;
    private String beneNm;
    private String beneAddr1;
    private String beneAddr2;
    private String beneAddr3;
    private String befoCcy;
    private int befoAmt;
    private int incAmt;
    private int decAmt;
    private String amdCcy;
    private int amdAmt;
    private Date expIl;
    private Date shipIl;
    private String reimBic;
    private String reimNm;
    private String chargeGb;
    private String partShip;
    private String tranShip;
    private String raGb;
    private String orgnNm1;
    private String orgnNm2;
    private String priceNm;
    private String fromPort;
    private String toPort;
    private String amtMore;
    private String amtLess;
    private String operNo;
    private String mt707Nm;
    private String mt747Nm;
    private String applCd;
    private String ediGb;
    private String ediCust;
    private String ediSend;
    private Date ediSndIl;
    private String ediJumNo;
    private int ediSeqNo;
    private String ediSfnm;
    private String ediRcv;
    private Date ediRcvIl;
    private String ediRfnm;
    private String thrNm;
    private String sendJumgb;
    private String bankGb;
    private String ncuBefoCcy;
    private int ncuBefoAmt;
    private int ncuIncAmt;
    private int ncuDecAmt;
    private String ncuAmdCcy;
    private int ncuAmdAmt;
    private int hisNo;
    private String cbsGb;
    private String mngInfo;
    private String presPrd;
    private String loadPort;
    private String discPort;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String applNm;
    private String applAddr1;
    private String applAddr2;
    private String applAddr3;
    private String purposeCd;
    private String cancelCd;
    private String transGb;
    private String applRule;
    private String applRule2;
    private String negoGb;
    private String usanTerm;
    private String termGb;
    private String termType;
    private String draftRate;
    private String draweeBic;
    private String draweeNm;
    private String cnfmBic;
    private String cnfmNm;
    private String thrNm2;
    private String thrNm3;
    private String thrNm4;
    private String negoBic;
    private String ttreimGb;
    private String cnfmGb;
    private String thrBic;
} 
