package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_ADH_AMEND") 
@Data 
public class AFEX_ADH_AMENDInfo implements Serializable { 
@Id 
@GeneratedValue 
private String mt707DocId; 
private String beneCd; 
private Date gyobuIl; 
private String ediChuri; 
private String buseoNo; 
private String mngNo; 
private String drawBknm3; 
private String reimBkcd; 
private Date updDt; 
private String amdCcy; 
private String drawBknm2; 
private String drawBkcd; 
private String drawBknm1; 
private String norUrg; 
private Date expIl; 
private String faxSend; 
private int mt708Cnt; 
private int brCharge; 
private int chargeAmt; 
private int totSeq; 
private String regEmpNo; 
private String thruBkcd; 
private Date chargeIl; 
private String lstTime; 
private String thruBknm1; 
private String afCcy; 
private String thruBknm2; 
private String thruBknm3; 
private Date cnfrFrIl; 
private String advNo; 
private String sendGb; 
private String ourCustGb; 
private String ibgmMd; 
private int amdAmt; 
private String ediSuin; 
private int seqNo; 
private String tongPrint; 
private int cnfrRt; 
private String mt707Fnm2; 
private String mt707Fnm1; 
private String mt730DocId; 
private String mt707Fnm4; 
private String mt707Fnm3; 
private String txKey; 
private String swiftMrn; 
private String chargeCcy; 
private String ediId; 
private String tail; 
private Date makeIl; 
private String applNm4; 
private String applNm3; 
private String cnfmBic; 
private int afAmt; 
private String mt710Send; 
private String applNm2; 
private String applNm1; 
private String advThruGb; 
private String updEmpNo; 
private String condSts; 
private int mt707Cnt; 
private String reimBknm3; 
private String reimBknm2; 
private String reimBknm1; 
private String authGb; 
private Date lstIl; 
private String amtGb; 
private String opNo; 
private String amdGb; 
private Date shipIl; 
private String chargeMd; 
private String mt730Send; 
private String mt708Fnm1; 
private String faxAdv; 
private String msgType; 
private String mt708Fnm4; 
private String mt708Fnm2; 
private String mt707Fnm; 
private int prtCnt; 
private String mt708Fnm3; 
private Date openIl; 
private String openBkcd; 
private String brNm; 
private String lcNo; 
private String ediSend; 
private String relay; 
private String mt710DocId; 
private String brNo; 
private int lstHisNo; 
private Date cnfrToIl; 
private String reIssue; 
private String gyobuGb; 
private String beneNm2; 
private Date regDt; 
private String beneNm3; 
private String beneNm1; 
private int amdCnt; 
private String cixNo; 
private Date firstIl; 
private String chargeGb; 
private String openBknm2; 
private String openBknm1; 
private String openBknm3; 
private String cnfmNm1; 
private String cnfmNm3; 
private String cnfmNm2; 
private String confirmGb; 
private String updTm; 
private String beneNm4; 
private String bokSend; 
private String regTm; 
} 
