package nhbank.core.domain;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afexXpbBase")
@Data
public class AFEX_XPB_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String ikisSts;
    private String bkGb;
    private String cixNo;
    private String comNo;
    private String buseoNo;
    private String mngInfo;
    private BigDecimal xpJan;
    private BigDecimal budoJan;
    private BigDecimal misuBjan;
    private BigDecimal misuJan;
    private BigDecimal lessSumAmt;
    private BigDecimal overSumAmt;
    private BigDecimal csSumAmt;
    private BigDecimal jiSeq;
    private BigDecimal setSeq;
    private BigDecimal budoSeq;
    private Date negoIl;
    private Date gisIl;
    private Date lstIl;
    private Date lstIbIl;
    private String negoCcy;
    private BigDecimal negoAmt;
    private String xpGb;
    private String negoGb;
    private String bonjiGb;
    private String tenorGb;
    private String oaGb;
    private String hjIlCd;
    private Date manGijIl;
    private String hajaMngInfo;
    private String halGb;
    private BigDecimal comRt;
    private BigDecimal comAmt;
    private BigDecimal intRt;
    private BigDecimal intAmt;
    private BigDecimal hijaTerm;
    private BigDecimal usanceTerm;
    private String hsCd;
    private String spNm;
    private String xpType;
    private String sdCtry;
    private String priceCd;
    private String openBkcd;
    private String setBkcd;
    private String depoBkcd;
    private String reneBkcd;
    private BigDecimal jasaAmt;
    private BigDecimal tasaAmt;
    private String trefNo;
    private String openBknm;
    private String reDepoGb;
    private String ipNm;
    private Date shipIl;
    private String invoiceNo;
    private String singoNo;
    private String reneReqGb;
    private String reneGb;
    private Date reneAcIl;
    private Date reneGisIl;
    private String reneOrefNo;
    private BigDecimal reneTerm;
    private BigDecimal r2Frt;
    private BigDecimal r2Fee;
    private BigDecimal r2IjaAmt;
    private String caCcy;
    private BigDecimal caAmt;
    private BigDecimal insuAmt;
    private BigDecimal jiAmt;
    private BigDecimal setAmt;
    private Date hmanIl;
    private Date ymanIl;
    private Date ydcIl;
    private Date budoIl;
    private BigDecimal budoAmt;
    private BigDecimal budoSamt;
    private Date misuIl;
    private String obcrGb;
    private Date budoLisuIl;
    private Date lstCaIl;
    private Date moJubIl;
    private Date moBalIl;
    private String balGb;
    private BigDecimal miGun;
    private BigDecimal miplGun;
    private String hdSngNo;
    private Date ijaLisuIl;
    @Column(name = "LST_IJA_HRT")
    private BigDecimal lstIjaHrt;
    @Column(name = "LST_IJA_H_RT")
    private BigDecimal lstIjaHRt;
    private String gaWijaGb;
    private String ijaMjGb1;
    private String ijaMjGb2;
    private String ijaHcGb;
    private String bdIjaGb;
    private String ftpRtGb;
    private BigDecimal ftpRt;
    private BigDecimal ikisHisNo;
    private BigDecimal ikisIjAmt;
    private String opNo;
    private String ownerNo;
    private String pbrmNo;
    private Date turnIl;
    private BigDecimal aaTraCnt;
    private BigDecimal caTraCnt;
    private BigDecimal dlTraCnt;
    private String coverGb;
    private Date lstIsuIl;
    private Date bdDelayIl;
    private String gyom;
    private String reimGb;
    private String reimBkcd;
    private String chgNegoYn;
    private String mngInfo2;
    private String comId;
    private String tsLcYn;
    private String tsAdvNo;
    private BigDecimal tsSeqNo;
    private BigDecimal tsNegoAmt;
    private String raRefNo;
    private BigDecimal raClmCnt;
    private String ibfGb;
    private String whanRcvGb;
    private BigDecimal rptAmt1;
    private BigDecimal rptAmt2;
    private BigDecimal rptAmt3;
    private BigDecimal rptAmt4;
    private BigDecimal rptAmt5;
    private String rptAcct1;
    private String boseGb;
    private BigDecimal payableAmt;
    private String actpayRefNo1;
    private String suspayRefNo1;
    private String suspayRefNo2;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
