package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afexRohBase")
@Data
public class AFEX_ROH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String cixNo;
    private String bkGb;
    private String mngInfo;
    private String upmuGb;
    private Date acIl;
    private Date gisIl;
    private Date lstIl;
    private Date lstIbIl;
    private String ibjiMd;
    private Date setIl;
    private Date setGisIl;
    private String rtCd;
    private String tsCd;
    private String ccy;
    private BigDecimal famt;
    private String ddType;
    private String ddNo;
    private String sdCtry;
    private String jucheCd;
    private String geojuGb;
    private String sayuCd;
    private String junGb;
    private String junNo1;
    private String applIdNo;
    private String applIdNoGb;
    private String applNation;
    private String applPostNo;
    private String vipCd;
    private String sjGb;
    private String rcvIdNo;
    private String rcvIdNoGb;
    private String setBkcd;
    private String setBknm;
    private String remitDepo;
    private Date ydaeIl;
    private String jijungCd;
    private String idNo;
    private String idNoGb;
    private String jigbNo;
    private BigDecimal jigbSeq;
    private BigDecimal chAmt;
    private String chGb;
    private String junNo2;
    private String mjGb;
    private String cdSngNo;
    private BigDecimal cdSilSeq;
    private String opNo;
    private String ownerNo;
    private String pbrmNo;
    private Date sdTrIl;
    private String jiOkNo;
    private BigDecimal mileage;
    private String phIdNo;
    private BigDecimal phSeqNo;
    private String ydGuja;
    private String canGb;
    private Date debitVdate;
    private String debitCur;
    private BigDecimal debitAmt;
    private String stateMsg;
    private String emailNm;
    private Date makeIl;
    private String mttypeCode;
    private String outMsg;
    private String moneyMsg;
    private Date valueDate;
    private String rcvBic;
    private String rcvName1;
    private String rcvName2;
    private String rcvName3;
    private String applNm1;
    private String applNm2;
    private String applAddr1;
    private String applAddr2;
    private String applAddr3;
    private String rcvNm1;
    private String rcvNm2;
    private String rcvAddr1;
    private String rcvAddr2;
    private String rcvAddr3;
    private String rcvAcctNo;
    private String rcvBkcd;
    private String rcvBkAcno;
    private String rcvBknm1;
    private String rcvBknm2;
    private String rcvBkAddr1;
    private String rcvBkAddr2;
    private String rcvBkAddr3;
    private String interBic;
    private String interName1;
    private String interName2;
    private String interName3;
    private String infoName1;
    private String infoName2;
    private String infoName3;
    private String infoName4;
    private String info72Name1;
    private String info72Name2;
    private String info72Name3;
    private String info72Name4;
    private String info72Name5;
    private String info72Name6;
    private BigDecimal cableChg;
    private BigDecimal liftChg;
    private BigDecimal cashChg;
    private BigDecimal exchChg;
    private BigDecimal payComm;
    private String boseGb;
    private String paidOption;
    private String instructCcy;
    private BigDecimal instructAmt;
    private BigDecimal exRate;
    private String bopSeqNo;
    private String bopTrxCode;
    private String bopTrxRemark;
    private String tradeGb;
    private String subDpNo;
    private String cvtCcy;
    private BigDecimal cvtAmt;
    private BigDecimal cvtExrate;
    private String fxCcy;
    private BigDecimal fxAmt;
    private BigDecimal fxExrate;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
