package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFEX_IPB_BASE") 
@Data 
public class AFEX_IPB_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private String buseoNo; 
private String hsCd; 
private int tcFrt; 
private int djbBjan; 
private Date updDt; 
private Date expIl; 
private String regEmpNo; 
private String openCcy; 
private Date gisIl; 
private String reOpGb; 
private String ownerNo; 
private int corSeq; 
private int lguJan; 
private int ikisHisNo; 
private int bojJan; 
private String tcTermGb; 
private int jajSeq; 
private String slYoCd; 
private String priceCd; 
private int term; 
private int bldSeq; 
private String bunGb; 
private int lgsJan; 
private int gtJan; 
private String ipCd; 
private String bkGb; 
private String ibfGb; 
private int lgmSeq; 
private int tolJan; 
private int corJan; 
private int itmSeq; 
private String boseGb; 
private String comId; 
private int bojBjan; 
private String hsNm; 
private int corFrt; 
private int bojJukYul; 
private String gyom; 
private int insJan; 
private String tcRcvGb; 
private String termGb; 
private int bldJan; 
private String setBkcd; 
private String updEmpNo; 
private int tcHrt; 
private String poNo; 
private String acptBkcd; 
private int openAmt; 
private Date lstIl; 
private String opNo; 
private String pbrmNo; 
private String amtMore; 
private String sdCtry; 
private String slCd; 
private String tcFrtGb; 
private int bojBjan2; 
private int ikisSeq; 
private String reReGb; 
private int bojBjan1; 
private String canAccGb; 
private String skbdnYn; 
private Date openIl; 
private String hdSngNo; 
private String unsongGb; 
private String beniCtry; 
private int bojJan2; 
private int djbSeq; 
private int bojJan1; 
private int tcFrt2; 
private String ipCcy; 
private String reReGb1; 
private Date tcLisuIl; 
private String lcNo; 
private int tcDsamt; 
private int sprdFrt; 
private String refNo; 
private int reFrtYul; 
private int amdSeq; 
private String origCtry; 
private int tcMisuCnt; 
private Date regDt; 
private int tcDsamt2; 
private String ikisSts; 
private String beniNm; 
private Date lstIbIl; 
private String cixNo; 
private int tolUse; 
private String amtLess; 
private String reopBkcd; 
private String partshipGb; 
private int bojSeq; 
private int ipJan; 
private String confBkcd; 
private String updTm; 
private String revolveGb; 
private String miltGb; 
private String regTm; 
} 
