package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afexRihBase")
@Data
public class AFEX_RIH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private Date rcvIl;
    private BigDecimal seqNo;
    private String rtCd;
    private String moneyCd;
    private String rcvGb;
    private Date makeIl;
    private String refNo;
    private String rcvBr;
    private String cixNo;
    private String bkGb;
    private String mngInfo;
    private String upmuGb;
    private Date acIl;
    private Date gisIl;
    private Date lstIl;
    private Date lstIbIl;
    private String ibjiMd;
    private Date acIl2;
    private Date gisIl2;
    private String junGb;
    private String operId;
    private String mngrId;
    private String ccy;
    private BigDecimal famt;
    private BigDecimal orgFamt;
    private String ddNo;
    private String theirRefNo;
    private String sdCtry;
    private String jucheCd;
    private String geojuGb;
    private String sayuCd;
    private String jukyo;
    private String junNo;
    private String chGb;
    private BigDecimal chAmt;
    private String mjGb;
    private String rcvNation;
    private String rcvIdNo;
    private String rcvIdNoGb;
    private String rcvBuseoNo;
    private String rcvPostNo;
    private String sjGb;
    private String vipCode;
    private String ownerNo;
    private String pbrmNo;
    private Date jungjiIl;
    private Date sagoIl;
    private Date negoCertiIl;
    private BigDecimal mileage;
    private String ydGuja;
    private BigDecimal feeCnt;
    private String feeMsg;
    private String inmsgGb;
    private String inMsg;
    private String stateMsg;
    private String mndGb;
    private String creditCur;
    private BigDecimal creditAmt;
    private Date creditIl;
    private String applNm;
    private String applAddr1;
    private String applAddr2;
    private String applAddr3;
    private String apliAcno;
    private String jgDepoCd;
    private String jgDepoNm;
    private String jgBkcd;
    private String jgBkAbano;
    private String jgBknm;
    private String jgBkAddr1;
    private String jgBkAddr2;
    private String jgBkAddr3;
    private String rcvNm;
    private String rcvAddr1;
    private String rcvAddr2;
    private String rcvAddr3;
    private String rcvTelNo;
    private String rcvAcctNo;
    private String depoCode;
    private String depoName1;
    private String sbankBkcd;
    private String sbankBknm;
    private String sbankAddr1;
    private String sbankAddr2;
    private String sbankAddr3;
    private String cbankBkcd;
    private String cbankBknm;
    private String cbankAddr1;
    private String cbankAddr2;
    private String cbankAddr3;
    private Date valueDate;
    private String feeCur;
    private BigDecimal feeAmt;
    private String info70Name1;
    private String info70Name2;
    private String info70Name3;
    private String info70Name4;
    private String infoName1;
    private String infoName2;
    private String infoName3;
    private String infoName4;
    private String infoName5;
    private String infoName6;
    private String imad;
    private String preImad;
    private String outmsgGb;
    private String outmsgAutoYn;
    private String outMsg;
    private String moneyMsg;
    private Date outmakeIl;
    private BigDecimal outAmt;
    private BigDecimal outComm;
    private BigDecimal outFee;
    private String mttypeCode;
    private String errNo;
    private String errMsg;
    private String refundGb;
    private String refundRefNo;
    private String refundTheirRef;
    private String refundRemark;
    private String intBkcd;
    private String intBknm;
    private String intBkAddr1;
    private String intBkAddr2;
    private String intBkAddr3;
    private String intBkAcct;
    private String jgBkAcct;
    private String msgType;
    private String relatedRef;
    private String boseGb;
    private String exportSetlGb;
    private String tradeGb;
    private String instructCcy;
    private BigDecimal instructAmt;
    private BigDecimal exRate;
    private String bopSeqNo;
    private String bopTrxCode;
    private String bopTrxRemark;
    private String subDpNo;
    private String cvtCcy;
    private BigDecimal cvtAmt;
    private BigDecimal cvtExrate;
    private String cableChgCcy;
    private BigDecimal cableChgAmt;
    private String holdRemark1;
    private String holdRemark2;
    private String holdRemark3;
    private String holdRemark4;
    private String holdRemark5;
    private String holdRemark6;
    private String holdRemark7;
    private String holdRemark8;
    private String mngBr;
    private String sts;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
    private String vcbFeeGb;
    private String vcbFeeCcy;
    private BigDecimal vcbFeeAmt;
} 
