package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

@Entity
@Table(name = "AFIF_FEH_BASE")
@Data
public class AFIF_FEH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String comId;
    private String comNm;
    private String counterpartyId;
    private String counterpartyNm;
    private String dealType;
    private Date dealIl;
    private String baseCcy;
    private String cptyCcy;
    private String nearValueIlGb;
    private Date nearValueIl;
    private int nearExHrt;
    private String nearBuyCcy;
    private int nearBuyAmt;
    private String nearSellCcy;
    private int nearSellAmt;
    private String nearInputGb;
    private int nearUsdCvtAmt;
    private int nearCustUsdAmt;
    private int nearBaseCvtAmt;
    private int nearBrHrt;
    private String nearKrusDealer;
    private int nearKrusHrt;
    private String nearOurRcvDepoCd;
    private String nearOurRcvDepoNm;
    private String nearOurPayDepoCd;
    private String nearOurPayDepoNm;
    private String nearThrRcvDepoBic;
    private String nearThrRcvDepoNm;
    private String nearConfirmYn;
    private Date nearConfirmIl;
    private String nearPoYn;
    private Date nearPoIl;
    private int nearPoSeq;
    private String farValueIlGb;
    private Date farValueIl;
    private int farExHrt;
    private String farBuyCcy;
    private int farBuyAmt;
    private String farSellCcy;
    private int farSellAmt;
    private String farInputGb;
    private int farUsdCvtAmt;
    private int farCustUsdAmt;
    private int farBaseCvtAmt;
    private int farBrHrt;
    private String farKrusDealer;
    private int farKrusHrt;
    private String farOurRcvDepoCd;
    private String farOurRcvDepoNm;
    private String farOurPayDepoCd;
    private String farOurPayDepoNm;
    private String farThrRcvDepoBic;
    private String farThrRcvDepoNm;
    private String farConfirmYn;
    private Date farConfirmIl;
    private String farPoYn;
    private Date farPoIl;
    private int farPoSeq;
    private String onoffGb;
    private String inoutGb;
    private String dealMatchType;
    private int swapHrt;
    private String dealGb;
    private String interCustType;
    private String brNo;
    private String sbrNo;
    private String outofRiskGb;
    private String linkedRefNo;
    private Date rateFixIl;
    private int fixExHrt;
    private String setlCcy;
    private String setlAmtGb;
    private int setlAmt;
    private Date setlIl;
    private String nearSngNo;
    private String farSngNo;
    private String systemGb;
    private String bankCd;
    private String changeBrSts;
    private String interfaceGb;
    private String nearBbsYn;
    private String farBbsYn;
    private String fwdEbsYn;
    private Date fstIbIl;
    private Date lstDealIl;
    private Date lstIbIl;
    private int hisNo;
    private String dealerId;
    private String userId;
    private String kondorId;
    private String linkedDeal;
    private int nearSpotHrt;
    private int farSpotHrt;
    private int nearBuyBoj;
    private int nearSellBoj;
    private int farBuyBoj;
    private int farSellBoj;
    private String hdSngNo;
    private String beHdSngno;
    private String remark;
    private String pvpYn;
    private String biCustSts;
    private String biNonBankCd;
    private String biBankCd;
    private String biDealPps;
    private String biBusinessActType;
    private String biCntyCd;
    private String biCcy;
    private String brokerId;
    private String brokerFeeCcy;
    private int brokerFeeAmt;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
