package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFIF_FEH_BASE") 
@Data 
public class AFIF_FEH_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private int brokerFeeAmt; 
private String biCustSts; 
private String onoffGb; 
private String farOurRcvDepoCd; 
private String userId; 
private int farSpotHrt; 
private String changeBrSts; 
private String pvpYn; 
private String dealGb; 
private Date lstDealIl; 
private Date updDt; 
private String nearPoYn; 
private int nearBaseCvtAmt; 
private Date setlIl; 
private String regEmpNo; 
private String nearThrRcvDepoNm; 
private int farBuyAmt; 
private String kondorId; 
private String nearSellCcy; 
private int farSellAmt; 
private int farCustUsdAmt; 
private int nearUsdCvtAmt; 
private Date farValueIl; 
private int farBrHrt; 
private String nearOurPayDepoNm; 
private int farBaseCvtAmt; 
private String setlCcy; 
private String nearConfirmYn; 
private String farPoYn; 
private Date dealIl; 
private int farPoSeq; 
private String dealType; 
private Date farPoIl; 
private String biNonBankCd; 
private Date nearConfirmIl; 
private int nearSpotHrt; 
private String remark; 
private int swapHrt; 
private int nearBuyAmt; 
private String farBbsYn; 
private String comId; 
private Date nearValueIl; 
private String nearBbsYn; 
private String interCustType; 
private Date fstIbIl; 
private int nearBuyBoj; 
private String interfaceGb; 
private String farOurPayDepoCd; 
private String farBuyCcy; 
private String counterpartyNm; 
private String farSellCcy; 
private int nearSellBoj; 
private int nearPoSeq; 
private String biDealPps; 
private String updEmpNo; 
private int nearKrusHrt; 
private String dealMatchType; 
private int farExHrt; 
private String systemGb; 
private String comNm; 
private String farThrRcvDepoNm; 
private String farConfirmYn; 
private String nearOurRcvDepoCd; 
private String baseCcy; 
private int nearSellAmt; 
private String setlAmtGb; 
private String farInputGb; 
private String farThrRcvDepoBic; 
private Date farConfirmIl; 
private String cptyCcy; 
private String nearOurPayDepoCd; 
private int hisNo; 
private int nearCustUsdAmt; 
private int nearBrHrt; 
private String farOurRcvDepoNm; 
private String nearInputGb; 
private String nearThrRcvDepoBic; 
private String hdSngNo; 
private int fixExHrt; 
private String linkedRefNo; 
private int farKrusHrt; 
private String farSngNo; 
private String linkedDeal; 
private String brokerFeeCcy; 
private String biCcy; 
private String farKrusDealer; 
private String nearKrusDealer; 
private int farSellBoj; 
private String biBusinessActType; 
private String farValueIlGb; 
private String fwdEbsYn; 
private String nearBuyCcy; 
private String refNo; 
private int nearExHrt; 
private String farOurPayDepoNm; 
private String brNo; 
private String nearValueIlGb; 
private String counterpartyId; 
private int farBuyBoj; 
private Date regDt; 
private Date lstIbIl; 
private Date nearPoIl; 
private String bankCd; 
private String inoutGb; 
private Date rateFixIl; 
private String nearOurRcvDepoNm; 
private int setlAmt; 
private String nearSngNo; 
private String beHdSngno; 
private int farUsdCvtAmt; 
private String sbrNo; 
private String dealerId; 
private String outofRiskGb; 
private String biBankCd; 
private String updTm; 
private String brokerId; 
private String biCntyCd; 
private String regTm; 
} 
