package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFIF_MMH_BASE") 
@Data 
public class AFIF_MMH_BASEInfo implements Serializable { 
@Id 
@GeneratedValue 
private Date confirmIl; 
private String thrRcvDepoCcy; 
private int brokerFeeAmt; 
private String ourRcvDepoCd; 
private String intCcy; 
private String onoffGb; 
private String updEmpNo; 
private String userId; 
private String changeBrSts; 
private String intAtMatYn; 
private int taxAmt; 
private String comNm; 
private Date intFromIl; 
private Date lstDealIl; 
private String borrowKind; 
private Date updDt; 
private String rolloverYn; 
private String holiDayRule; 
private Date expIl; 
private int usdCvtAmt; 
private String bondRefNo; 
private String regEmpNo; 
private String kondorId; 
private String ourRcvDepoCcy; 
private String ourRcvDepoNm; 
private String upfrontFeeCcy; 
private String contractId; 
private String expYn; 
private String thrRcvDepoBic; 
private int principalAmt; 
private int spreadRt; 
private int indexRt; 
private int intAmt; 
private String confirmYn; 
private String borrowGb; 
private String advArrGb; 
private String nationLonGb; 
private Date intPayRcvIl; 
private int baseCvtAmt; 
private int totalRt; 
private String rolloverRefNo; 
private Date dealIl; 
private Date valueIl; 
private String accrType; 
private String holidayLocation; 
private String rateFreq; 
private int intDays; 
private String fixFltGb; 
private String brokerFeeCcy; 
private String singleBothType; 
private String refNo; 
private int upfrontFeeAmt; 
private String poYn; 
private String valueYn; 
private String counterpartyId; 
private String loanUseGb; 
private String borrowLonGb; 
private String remark; 
private String ourPayDepoCd; 
private Date regDt; 
private String bsnsDayRule; 
private int poAmt; 
private String intFreq; 
private String relateRefNo; 
private Date lstIbIl; 
private String comId; 
private Date poIl; 
private String rateGb; 
private String bankCd; 
private String inoutGb; 
private Date fstIbIl; 
private String couponAdjYn; 
private String ourPayDepoCcy; 
private String rolloverType; 
private int poSeq; 
private String dealerId; 
private String ccy; 
private Date intToIl; 
private String ourPayDepoNm; 
private String interofficeBrNo; 
private String updTm; 
private String thrRcvDepoNm; 
private String brokerId; 
private String counterpartyNm; 
private String rateCcy; 
private String regTm; 
} 
