package nhbank.core.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "afifFehBase")
@Data
public class AFIF_FEH_BASEInfo implements Serializable {
    @Id
    @GeneratedValue
    private String refNo;
    private String comId;
    private String comNm;
    private String counterpartyId;
    private String counterpartyNm;
    private String dealType;
    private Date dealIl;
    private String baseCcy;
    private String cptyCcy;
    private String nearValueIlGb;
    private Date nearValueIl;
    private BigDecimal nearExHrt;
    private String nearBuyCcy;
    private BigDecimal nearBuyAmt;
    private String nearSellCcy;
    private BigDecimal nearSellAmt;
    private String nearInputGb;
    private BigDecimal nearUsdCvtAmt;
    private BigDecimal nearCustUsdAmt;
    private BigDecimal nearBaseCvtAmt;
    private BigDecimal nearBrHrt;
    private String nearKrusDealer;
    private BigDecimal nearKrusHrt;
    private String nearOurRcvDepoCd;
    private String nearOurRcvDepoNm;
    private String nearOurPayDepoCd;
    private String nearOurPayDepoNm;
    private String nearThrRcvDepoBic;
    private String nearThrRcvDepoNm;
    private String nearConfirmYn;
    private Date nearConfirmIl;
    private String nearPoYn;
    private Date nearPoIl;
    private BigDecimal nearPoSeq;
    private String farValueIlGb;
    private Date farValueIl;
    private BigDecimal farExHrt;
    private String farBuyCcy;
    private BigDecimal farBuyAmt;
    private String farSellCcy;
    private BigDecimal farSellAmt;
    private String farInputGb;
    private BigDecimal farUsdCvtAmt;
    private BigDecimal farCustUsdAmt;
    private BigDecimal farBaseCvtAmt;
    private BigDecimal farBrHrt;
    private String farKrusDealer;
    private BigDecimal farKrusHrt;
    private String farOurRcvDepoCd;
    private String farOurRcvDepoNm;
    private String farOurPayDepoCd;
    private String farOurPayDepoNm;
    private String farThrRcvDepoBic;
    private String farThrRcvDepoNm;
    private String farConfirmYn;
    private Date farConfirmIl;
    private String farPoYn;
    private Date farPoIl;
    private BigDecimal farPoSeq;
    private String onoffGb;
    private String inoutGb;
    private String dealMatchType;
    private BigDecimal swapHrt;
    private String dealGb;
    private String interCustType;
    private String brNo;
    private String sbrNo;
    private String outofRiskGb;
    private String linkedRefNo;
    private Date rateFixIl;
    private BigDecimal fixExHrt;
    private String setlCcy;
    private String setlAmtGb;
    private BigDecimal setlAmt;
    private Date setlIl;
    private String nearSngNo;
    private String farSngNo;
    private String systemGb;
    private String bankCd;
    private String changeBrSts;
    private String interfaceGb;
    private String nearBbsYn;
    private String farBbsYn;
    private String fwdEbsYn;
    private Date fstIbIl;
    private Date lstDealIl;
    private Date lstIbIl;
    private BigDecimal hisNo;
    private String dealerId;
    private String userId;
    private String kondorId;
    private String linkedDeal;
    private BigDecimal nearSpotHrt;
    private BigDecimal farSpotHrt;
    private BigDecimal nearBuyBoj;
    private BigDecimal nearSellBoj;
    private BigDecimal farBuyBoj;
    private BigDecimal farSellBoj;
    private String hdSngNo;
    private String beHdSngno;
    private String remark;
    private String pvpYn;
    private String biCustSts;
    private String biNonBankCd;
    private String biBankCd;
    private String biDealPps;
    private String biBusinessActType;
    private String biCntyCd;
    private String biCcy;
    private String brokerId;
    private String brokerFeeCcy;
    private BigDecimal brokerFeeAmt;
    private String regEmpNo;
    private Date regDt;
    private String regTm;
    private String updEmpNo;
    private Date updDt;
    private String updTm;
} 
