package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFTR_FFH_COMM_TRSC_PTCL") 
@Data 
public class AFTR_FFH_COMM_TRSC_PTCLInfo implements Serializable { 
@Id 
@GeneratedValue 
private String DAT_DEL_CYC_CD; 
private int NORM_COMM_RT; 
private int OGN_TRSC_DTLS_SEQ_NO; 
private int RDU_COMM_RT; 
private String COMM_CD; 
private String RSEV_DAT; 
private String SVC_GRP_CD; 
private int SAPV_COMM_APC_SEQ_NO; 
private int TGT_NCNT; 
private Date TRSC_DT; 
private String FST_TRMS_SYS_CD; 
private String FUND_NO; 
private String BS_ATIT_CD; 
private int SBST_AMT; 
private String TRSC_SCRN_NO; 
private Date UPD_DT; 
private String GEAR_ACCT_NO; 
private int FEX_COMM_VLU; 
private String PRD_CD; 
private int APCL_COMM; 
private String OUR_CUST_YN; 
private Date TRM_END_DT; 
private String COMM_CUR_CD; 
private String REG_EMP_NO; 
private int CUST_PINT_DCTD_AMT; 
private int WDRW_AMT; 
private String CUST_NO; 
private String TRSC_TMNL_NO; 
private int APCL_IRRT; 
private String GLOB_ID; 
private String CAN_POSS_YN; 
private int COMM_CRRC_AMT; 
private int TRT_COMM; 
private Date NLVYD_PTCL_REG_DT; 
private String COMM_PRIM_METH_CD; 
private String COMM_TRSC_ST_CD; 
private String COMM_SUB_FCTY_CD; 
private Date CAN_OGN_TRSC_DT; 
private String PGM_ID; 
private String ACTG_BR_NO; 
private String COMM_EXM_MGNT_YN_STRN_CD; 
private int GEAR_ACCT_SEQ_NO; 
private String PROC_EMP_NO; 
private int RDU_TCNT; 
private String ACNM_NO; 
private String IB_UID; 
private String COMM_RMRK; 
private Date LST_TRSC_DT; 
private int TRM_MLTP; 
private String TRSC_AMT_CUR_CD; 
private Date ACTG_DT; 
private int ACCT_SEQ_NO; 
private int NORM_COMM; 
private String GEAR_ACCT_BNK_CD; 
private String AGNT_NM; 
private String APV_NO; 
private String COMM_PRIM_RSN_CD; 
private String UPD_EMP_NO; 
private int DTLS_CLAS_NO; 
private Date RDU_STR_DT; 
private String PL_ATIT_CD; 
private String PFMC_BR_NO; 
private String CHNL_TYP_CD; 
private String FEX_REFN_NO; 
private int NLVYD_PTCL_REG_NO; 
private String COMM_BIZ_KEY; 
private String OTHBR_BIL_CD; 
private String AGNT_ACNM_NO; 
private String COMM_CUST_NM; 
private String COMM_BIZ_DV_CD; 
private int CUST_MLGE_DCTD_AMT; 
private String RCV_PAYM_DV_CD; 
private int CAN_OGN_TRSC_SEQ_NO; 
private String RECV_SVC_CD; 
private int USD_AMT; 
private int APCL_EXHG_RT; 
private int CASH_AMT; 
private int COMM_CRRC_NCNT; 
private String COMM_LEVY_DV_CD; 
private Date TRM_STR_DT; 
private String OGN_TRSC_BR_NO; 
private Date COMM_STR_DT; 
private int RDU_POSS_TOTL_TCNT; 
private int COMM_TRSC_SEQ_NO; 
private String FUND_TRSC_TYP_CD; 
private String UNON_CD; 
private String AF_PROC_RNW_YN; 
private Date SYS_UPD_DT; 
private String COMM_VOLN_PRIM_RSN_CTT; 
private String ACCT_NO; 
private int SAPV_COMM_APC_DTLS_NO; 
private String COMM_FCTY_CD; 
private int TGT_AMT; 
private String ACNM_NO_DV_CD; 
private int COMM_TRSC_DTLS_SEQ_NO; 
private Date REG_DT; 
private Date RDU_END_DT; 
private String VRTL_ACCT_NO; 
private Date SYS_REG_DT; 
private int PRIM_COMM; 
private int OTHBR_AMT; 
private String TRSC_BR_NO; 
private int APCL_COMM_RT; 
private String TRSC_BRFC_CD; 
private String UPD_TM; 
private String REG_TM; 
} 
