package nhbank.core.domain; 
import lombok.Data; 
import javax.persistence.Entity; 
import javax.persistence.GeneratedValue; 
import javax.persistence.Id; 
import javax.persistence.Table; 
import java.io.Serializable; 
import java.sql.Date; 
@Entity 
@Table(name = "AFTR_FFH_COMM_TRSC_PTCL") 
@Data 
public class AFTR_FFH_COMM_TRSC_PTCLInfo implements Serializable { 
@Id 
@GeneratedValue 
private String datDelCycCd; 
private int normCommRt; 
private int ognTrscDtlsSeqNo; 
private int rduCommRt; 
private String commCd; 
private String rsevDat; 
private String svcGrpCd; 
private int sapvCommApcSeqNo; 
private int tgtNcnt; 
private Date trscDt; 
private String fstTrmsSysCd; 
private String fundNo; 
private String bsAtitCd; 
private int sbstAmt; 
private String trscScrnNo; 
private Date updDt; 
private String gearAcctNo; 
private int fexCommVlu; 
private String prdCd; 
private int apclComm; 
private String ourCustYn; 
private Date trmEndDt; 
private String commCurCd; 
private String regEmpNo; 
private int custPintDctdAmt; 
private int wdrwAmt; 
private String custNo; 
private String trscTmnlNo; 
private int apclIrrt; 
private String globId; 
private String canPossYn; 
private int commCrrcAmt; 
private int trtComm; 
private Date nlvydPtclRegDt; 
private String commPrimMethCd; 
private String commTrscStCd; 
private String commSubFctyCd; 
private Date canOgnTrscDt; 
private String pgmId; 
private String actgBrNo; 
private String commExmMgntYnStrnCd; 
private int gearAcctSeqNo; 
private String procEmpNo; 
private int rduTcnt; 
private String acnmNo; 
private String ibUid; 
private String commRmrk; 
private Date lstTrscDt; 
private int trmMltp; 
private String trscAmtCurCd; 
private Date actgDt; 
private int acctSeqNo; 
private int normComm; 
private String gearAcctBnkCd; 
private String agntNm; 
private String apvNo; 
private String commPrimRsnCd; 
private String updEmpNo; 
private int dtlsClasNo; 
private Date rduStrDt; 
private String plAtitCd; 
private String pfmcBrNo; 
private String chnlTypCd; 
private String fexRefnNo; 
private int nlvydPtclRegNo; 
private String commBizKey; 
private String othbrBilCd; 
private String agntAcnmNo; 
private String commCustNm; 
private String commBizDvCd; 
private int custMlgeDctdAmt; 
private String rcvPaymDvCd; 
private int canOgnTrscSeqNo; 
private String recvSvcCd; 
private int usdAmt; 
private int apclExhgRt; 
private int cashAmt; 
private int commCrrcNcnt; 
private String commLevyDvCd; 
private Date trmStrDt; 
private String ognTrscBrNo; 
private Date commStrDt; 
private int rduPossTotlTcnt; 
private int commTrscSeqNo; 
private String fundTrscTypCd; 
private String unonCd; 
private String afProcRnwYn; 
private Date sysUpdDt; 
private String commVolnPrimRsnCtt; 
private String acctNo; 
private int sapvCommApcDtlsNo; 
private String commFctyCd; 
private int tgtAmt; 
private String acnmNoDvCd; 
private int commTrscDtlsSeqNo; 
private Date regDt; 
private Date rduEndDt; 
private String vrtlAcctNo; 
private Date sysRegDt; 
private int primComm; 
private int othbrAmt; 
private String trscBrNo; 
private int apclCommRt; 
private String trscBrfcCd; 
private String updTm; 
private String regTm; 
} 
