package nhbank.core.model; 
import lombok.Data; 
import java.util.Date; 
@Data 
public class AACT_TRX_BASE_DTO { 
private int BOOK_HRT; 
private String BUSEO_NO; 
private String ACT_MACH; 
private int JAKI_AMT; 
private int BS_CNT; 
private String GEOR_CD; 
private String ACT_EVNT_CD_CTT; 
private String UPD_EMP_NO; 
private String ACT_CD; 
private int VOUCHER_NO; 
private String CDSNG_NO; 
private String TRX_BR; 
private String STS; 
private int CAN_HISNO; 
private Date UPD_DT; 
private Date UPD_DT; 
private String IB_TIME; 
private String MGR_NO; 
private Date CAN_IL; 
private Date CAN_IL; 
private String REG_EMP_NO; 
private String OP_NO; 
private Date GIS_IL; 
private Date GIS_IL; 
private int ETC3_AMT; 
private int HIS_NO; 
private String ACT_APLY_DV_CD; 
private int CCY_CNT; 
private Date IB_IL; 
private Date IB_IL; 
private int USD_AMT; 
private String DPYD_GB; 
private String VIP_GB; 
private String ACT_DSEQ; 
private String ACT_CCY; 
private int BASIC_HRT; 
private String IFRS_DV_CD; 
private String ID_NO; 
private String GLOB_ID; 
private String PL_ADD_YN; 
private String UPMU_CD; 
private int FDC_HDAMT; 
private int ETC1_AMT; 
private String ACT_DTYP; 
private int APPL_HRT; 
private int ACT_AMT; 
private Date AC_IL; 
private Date AC_IL; 
private String POS_KIND; 
private String ACT_BSPL_GB; 
private String REF_NO; 
private String IBF_GB; 
private int PL_CNT; 
private int ETC2_AMT; 
private int GOSI_HRT; 
private int DEMI_HRT; 
private String ACT_OVRD_APLY_CD; 
private Date REG_DT; 
private Date REG_DT; 
private String IBJI_MD; 
private String RM_NO; 
private int TRX_SEQ; 
private Date TRX_IL; 
private Date TRX_IL; 
private String CIX_NO; 
private String ACT_CJUM; 
private String ACT_MODE; 
private int FDC_AMT; 
private String THEIR_REFNO; 
private String ACT_TELL; 
private String ILGE_GB; 
private String ACT_SJUM; 
private String UPD_TM; 
private String REG_TM; 

public AACT_TRX_BASE_DTO() { 
} 
} 
