package nhbank.core.model; 
import lombok.Data; 
import java.util.Date; 
@Data 
public class ACOM_COMH_MSG_DTO { 
private String LST_TTY; 
private String CO_BKNM3; 
private String BE_DOC; 
private String CO_BKNM4; 
private String PRIO_YN; 
private String AP_TIME; 
private String UPD_EMP_NO; 
private String COND_STS; 
private String CO_BKNM1; 
private Date AP_IL;
private Date TKEY_IL;
private String TKEY_VAL; 
private String TLX_MNG_NO; 
private String REL_DOC; 
private String CO_BKNM2; 
private String TKEY_BKCD; 
private String ANS_BACK; 
private String AF_DOC; 
private String INOUT_TIME; 
private String TKEY_YN; 
private String TKEY_VAR; 
private String MOR_NO; 
private Date UPD_DT;
private String DONE_TIME; 
private String BRAN_PRINT; 
private String USER_KEY; 
private Date LST_IL;
private String REG_EMP_NO; 
private String DOC_ID; 
private String OP_NO; 
private String TELEX_NO; 
private String PREV_MOR; 
private String OUR_REF; 
private String DUP_YN; 
private String LST_TIME; 
private String MSG_TYPE; 
private String TKEY_CNI1; 
private String LST_OP_NO; 
private String CO_BKCD; 
private Date INOUT_IL;
private String PHYS_DIVI; 
private int MSG_AMT; 
private String TKEY_CNI2; 
private String IO_GB; 
private String GLOB_ID; 
private String ERR_MSG; 
private String UPMU_GB; 
private String TKEY_PREF; 
private int SEQ_NO; 
private String BR_NO; 
private String FLAG_1; 
private String PREV_TS; 
private String FLAG_2; 
private String FLAG_3; 
private Date REG_DT;
private String MSG_GB; 
private String TRAIL_GB; 
private Date DONE_IL;
private String PREV_MIR; 
private String AP_MNG_NO; 
private String TS_KEY; 
private String NETW_GB; 
private String MSG_CCY; 
private String TKEY_LINE; 
private String TYPE_GB; 
private String THEIR_REF; 
private Date MAKE_IL;
private String HEAD_PRINT; 
private String MIR_NO; 
private Date PREV_IL;
private String UPD_TM; 
private String MSG_FILE_NM; 
private String REG_TM; 

public ACOM_COMH_MSG_DTO() { 
} 
} 
