package nhbank.core.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class ADST_DPB_BASE_DTO {
    private String ACCT_NO;
    private String BASE_CCY;
    private String ACCT_CCY;
    private String DPT_BBS_CD;
    private String DPT_BS_CD;
    private String DPT_PL_CD;
    private String INT_PAY_GB;
    private String DPT_TYPE_GB;
    private BigDecimal INT_TERM_GB;
    private String INT_CAL_GB;
    private String INT_CAL_METH_CD;
    private String DAYS_CALC_METH_CD;
    private Date OPN_IL;
    private Date JAGUM_IL;
    private Date DPT_INT_CAL_IL;
    private Date JAN_CERTI_IL;
    private Date IS_IL;
    private Date YSD_IL;
    private Date CC_NG_IL;
    private Date DPT_MAN_IL;
    private Date ROLL_OVER_IL;
    private String PWD;
    private String EMP_PAY_ACCT_PWD;
    private BigDecimal BS_JAN;
    private BigDecimal CUR_JAN;
    private BigDecimal COLLAT_AMT;
    private BigDecimal OPEN_AMT;
    private BigDecimal CLS_AMT;
    private BigDecimal STOP_AMT;
    private BigDecimal LMT_BLK_AMT;
    private BigDecimal M_TERM;
    private BigDecimal D_TERM;
    private BigDecimal INT_PAY_CNT;
    private BigDecimal DPT_BASIC_RT;
    private BigDecimal DPT_NEGO_RT;
    private String TAX_CD;
    private BigDecimal TAX_RT;
    private String FTP_RT_GB;
    private BigDecimal FTP_RT;
    private BigDecimal LST_TRX_NO;
    private BigDecimal LST_DR_TRX_NO;
    private BigDecimal CLS_CNT;
    private String LON_BBS_CD;
    private String LON_BS_CD;
    private String LON_PL_CD;
    private BigDecimal FST_JAN;
    private BigDecimal MAX_JAN;
    private BigDecimal LON_SNG_AMT;
    private BigDecimal COL_LON_INT;
    private BigDecimal LON_PRCP_YC_INT;
    private BigDecimal LON_INT_YC_INT;
    private String LON_YD_CD;
    private String LON_RT_CD;
    private BigDecimal LON_RT;
    private BigDecimal PRCP_OVER_DUE_INT_RT;
    private BigDecimal INT_OVER_DUE_INT_RT;
    private Date LON_INT_CAL_IL;
    private Date LON_INT_RCV_IL;
    private Date LON_MAN_IL;
    private Date LON_TERM_IL;
    private Date LON_FST_YC_IL;
    private Date LST_IB_IL;
    private String LST_TIME;
    private Date SELF_MNG_IL;
    private BigDecimal OPEN_EXPT_AMT;
    private BigDecimal DUE_AMT;
    private BigDecimal DEP_CNT;
    private BigDecimal PREPAY_DAY;
    private Date NOTICE_IL;
    private String ACCT_TYPE;
    private String RESERVED1;
    private String INT_RT_DV;
    private BigDecimal BF_TM_INT;
    private BigDecimal BF_TM_TAX;
    private BigDecimal AMT1;
    private BigDecimal AMT2;
    private BigDecimal AMT3;
    private BigDecimal AMT4;
    private BigDecimal AMT5;
    private BigDecimal AMT6;
    private BigDecimal AMT7;
    private BigDecimal AMT8;
    private BigDecimal AMT9;
    private BigDecimal AMT10;
    private String CD1;
    private String CD2;
    private String CD3;
    private String CD4;
    private String CD5;
    private String CD6;
    private String CD7;
    private String CD8;
    private String CD9;
    private String CD10;
    private BigDecimal RT1;
    private BigDecimal RT2;
    private BigDecimal RT3;
    private BigDecimal RT4;
    private BigDecimal RT5;
    private Date DT1;
    private Date DT2;
    private Date DT3;
    private Date DT4;
    private Date DT5;
    private String REG_EMP_NO;
    private Date REG_DT;
    private String REG_TM;
    private String UPD_EMP_NO;
    private Date UPD_DT;
    private String UPD_TM;
    private String RAND_SALT;

    public ADST_DPB_BASE_DTO() {
    }
} 
