package nhbank.core.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class AFEX_IPB_BASE_DTO {
    private String REF_NO;
    private String IKIS_STS;
    private String BK_GB;
    private String CIX_NO;
    private String BUSEO_NO;
    private String IP_CCY;
    private BigDecimal IP_JAN;
    private BigDecimal GT_JAN;
    private BigDecimal LGS_JAN;
    private BigDecimal LGU_JAN;
    private BigDecimal BLD_JAN;
    private BigDecimal INS_JAN;
    private BigDecimal BOJ_JAN;
    private BigDecimal BOJ_JAN1;
    private BigDecimal BOJ_JAN2;
    private BigDecimal BOJ_BJAN;
    private BigDecimal BOJ_BJAN1;
    private BigDecimal BOJ_BJAN2;
    private BigDecimal COR_JAN;
    private BigDecimal DJB_BJAN;
    private BigDecimal BLD_SEQ;
    private BigDecimal AMD_SEQ;
    private BigDecimal LGM_SEQ;
    private BigDecimal IKIS_SEQ;
    private BigDecimal IKIS_HIS_NO;
    private BigDecimal COR_SEQ;
    private BigDecimal DJB_SEQ;
    private BigDecimal BOJ_SEQ;
    private BigDecimal JAJ_SEQ;
    private BigDecimal ITM_SEQ;
    private Date OPEN_IL;
    private Date GIS_IL;
    private Date LST_IL;
    private Date LST_IB_IL;
    private String OPEN_CCY;
    private BigDecimal OPEN_AMT;
    private String IP_CD;
    private String BUN_GB;
    private String MILT_GB;
    private Date EXP_IL;
    private BigDecimal BOJ_JUK_YUL;
    private String PRICE_CD;
    private String HS_CD;
    private String HS_NM;
    private String ORIG_CTRY;
    private String SD_CTRY;
    private String TERM_GB;
    private BigDecimal TERM;
    private String HD_SNG_NO;
    private String CAN_ACC_GB;
    private String PO_NO;
    private String UNSONG_GB;
    private String TC_FRT_GB;
    private BigDecimal TC_FRT;
    private Date TC_LISU_IL;
    private BigDecimal TC_DSAMT;
    private BigDecimal TC_HRT;
    private String TC_TERM_GB;
    private String TC_RCV_GB;
    private String SL_CD;
    private String SL_YO_CD;
    private String SET_BKCD;
    private String ACPT_BKCD;
    private String CONF_BKCD;
    private String RE_OP_GB;
    private String REOP_BKCD;
    private BigDecimal RE_FRT_YUL;
    private String RE_RE_GB;
    private String RE_RE_GB1;
    private String OP_NO;
    private String OWNER_NO;
    private String PBRM_NO;
    private BigDecimal COR_FRT;
    private BigDecimal SPRD_FRT;
    private String LC_NO;
    private String AMT_MORE;
    private String AMT_LESS;
    private String REVOLVE_GB;
    private String PARTSHIP_GB;
    private String GYOM;
    private String COM_ID;
    private String IBF_GB;
    private BigDecimal TC_MISU_CNT;
    private BigDecimal TC_FRT2;
    private BigDecimal TC_DSAMT2;
    private String BENI_CTRY;
    private String BOSE_GB;
    private String BENI_NM;
    private BigDecimal TOL_JAN;
    private BigDecimal TOL_USE;
    private String SKBDN_YN;
    private String REG_EMP_NO;
    private Date REG_DT;
    private String REG_TM;
    private String UPD_EMP_NO;
    private Date UPD_DT;
    private String UPD_TM;

    public AFEX_IPB_BASE_DTO() {
    }
} 
