package nhbank.core.model;

import lombok.Data;

import java.util.Date;

@Data
public class AFEX_IPB_BASE_DTO {
    private String REF_NO;
    private String IKIS_STS;
    private String BK_GB;
    private String CIX_NO;
    private String BUSEO_NO;
    private String IP_CCY;
    private int IP_JAN;
    private int GT_JAN;
    private int LGS_JAN;
    private int LGU_JAN;
    private int BLD_JAN;
    private int INS_JAN;
    private int BOJ_JAN;
    private int BOJ_JAN1;
    private int BOJ_JAN2;
    private int BOJ_BJAN;
    private int BOJ_BJAN1;
    private int BOJ_BJAN2;
    private int COR_JAN;
    private int DJB_BJAN;
    private int BLD_SEQ;
    private int AMD_SEQ;
    private int LGM_SEQ;
    private int IKIS_SEQ;
    private int IKIS_HIS_NO;
    private int COR_SEQ;
    private int DJB_SEQ;
    private int BOJ_SEQ;
    private int JAJ_SEQ;
    private int ITM_SEQ;
    private Date OPEN_IL;
    private Date GIS_IL;
    private Date LST_IL;
    private Date LST_IB_IL;
    private String OPEN_CCY;
    private int OPEN_AMT;
    private String IP_CD;
    private String BUN_GB;
    private String MILT_GB;
    private Date EXP_IL;
    private int BOJ_JUK_YUL;
    private String PRICE_CD;
    private String HS_CD;
    private String HS_NM;
    private String ORIG_CTRY;
    private String SD_CTRY;
    private String TERM_GB;
    private int TERM;
    private String HD_SNG_NO;
    private String CAN_ACC_GB;
    private String PO_NO;
    private String UNSONG_GB;
    private String TC_FRT_GB;
    private int TC_FRT;
    private Date TC_LISU_IL;
    private int TC_DSAMT;
    private int TC_HRT;
    private String TC_TERM_GB;
    private String TC_RCV_GB;
    private String SL_CD;
    private String SL_YO_CD;
    private String SET_BKCD;
    private String ACPT_BKCD;
    private String CONF_BKCD;
    private String RE_OP_GB;
    private String REOP_BKCD;
    private int RE_FRT_YUL;
    private String RE_RE_GB;
    private String RE_RE_GB1;
    private String OP_NO;
    private String OWNER_NO;
    private String PBRM_NO;
    private int COR_FRT;
    private int SPRD_FRT;
    private String LC_NO;
    private String AMT_MORE;
    private String AMT_LESS;
    private String REVOLVE_GB;
    private String PARTSHIP_GB;
    private String GYOM;
    private String COM_ID;
    private String IBF_GB;
    private int TC_MISU_CNT;
    private int TC_FRT2;
    private int TC_DSAMT2;
    private String BENI_CTRY;
    private String BOSE_GB;
    private String BENI_NM;
    private int TOL_JAN;
    private int TOL_USE;
    private String SKBDN_YN;
    private String REG_EMP_NO;
    private Date REG_DT;
    private String REG_TM;
    private String UPD_EMP_NO;
    private Date UPD_DT;
    private String UPD_TM;

    public AFEX_IPB_BASE_DTO() {
    }
} 
