package nhbank.core.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class AFTR_FFH_COMM_TRSC_PTCL_DTO {
    private String TRSC_BR_NO;
    private Date TRSC_DT;
    private BigDecimal COMM_TRSC_SEQ_NO;
    private BigDecimal COMM_TRSC_DTLS_SEQ_NO;
    private Date SYS_REG_DT;
    private Date SYS_UPD_DT;
    private String COMM_TRSC_ST_CD;
    private String COMM_CD;
    private Date COMM_STR_DT;
    private String COMM_FCTY_CD;
    private String COMM_SUB_FCTY_CD;
    private String AF_PROC_RNW_YN;
    private String COMM_BIZ_DV_CD;
    private String CUST_NO;
    private String ACNM_NO;
    private String ACCT_NO;
    private BigDecimal ACCT_SEQ_NO;
    private String APV_NO;
    private String ACNM_NO_DV_CD;
    private Date ACTG_DT;
    private String ACTG_BR_NO;
    private String PRD_CD;
    private String FUND_NO;
    private String FUND_TRSC_TYP_CD;
    private String RCV_PAYM_DV_CD;
    private String PROC_EMP_NO;
    private String FST_TRMS_SYS_CD;
    private String GLOB_ID;
    private String CHNL_TYP_CD;
    private String SVC_GRP_CD;
    private String RECV_SVC_CD;
    private String TRSC_SCRN_NO;
    private String PGM_ID;
    private String DAT_DEL_CYC_CD;
    private String CAN_POSS_YN;
    private String TRSC_BRFC_CD;
    private String TRSC_TMNL_NO;
    private String PL_ATIT_CD;
    private String BS_ATIT_CD;
    private String COMM_PRIM_METH_CD;
    private String COMM_PRIM_RSN_CD;
    private String COMM_LEVY_DV_CD;
    private BigDecimal SAPV_COMM_APC_SEQ_NO;
    private BigDecimal SAPV_COMM_APC_DTLS_NO;
    private String TRSC_AMT_CUR_CD;
    private BigDecimal TGT_AMT;
    private BigDecimal TGT_NCNT;
    private String COMM_CUR_CD;
    private BigDecimal NORM_COMM;
    private BigDecimal APCL_COMM;
    private BigDecimal FEX_COMM_VLU;
    private BigDecimal PRIM_COMM;
    private BigDecimal CUST_PINT_DCTD_AMT;
    private BigDecimal CUST_MLGE_DCTD_AMT;
    private BigDecimal COMM_CRRC_NCNT;
    private BigDecimal COMM_CRRC_AMT;
    private BigDecimal NORM_COMM_RT;
    private BigDecimal APCL_COMM_RT;
    private BigDecimal APCL_EXHG_RT;
    private BigDecimal RDU_COMM_RT;
    private BigDecimal CASH_AMT;
    private BigDecimal SBST_AMT;
    private BigDecimal OTHBR_AMT;
    private String OTHBR_BIL_CD;
    private String FEX_REFN_NO;
    private String GEAR_ACCT_BNK_CD;
    private String GEAR_ACCT_NO;
    private BigDecimal GEAR_ACCT_SEQ_NO;
    private BigDecimal DTLS_CLAS_NO;
    private Date TRM_STR_DT;
    private Date TRM_END_DT;
    private Date NLVYD_PTCL_REG_DT;
    private BigDecimal NLVYD_PTCL_REG_NO;
    private String COMM_BIZ_KEY;
    private Date CAN_OGN_TRSC_DT;
    private BigDecimal CAN_OGN_TRSC_SEQ_NO;
    private BigDecimal OGN_TRSC_DTLS_SEQ_NO;
    private String OGN_TRSC_BR_NO;
    private String COMM_CUST_NM;
    private String COMM_RMRK;
    private Date LST_TRSC_DT;
    private String COMM_EXM_MGNT_YN_STRN_CD;
    private String RSEV_DAT;
    private BigDecimal TRT_COMM;
    private BigDecimal RDU_TCNT;
    private Date RDU_STR_DT;
    private BigDecimal RDU_POSS_TOTL_TCNT;
    private Date RDU_END_DT;
    private String AGNT_ACNM_NO;
    private String AGNT_NM;
    private String UNON_CD;
    private String OUR_CUST_YN;
    private String IB_UID;
    private BigDecimal TRM_MLTP;
    private BigDecimal APCL_IRRT;
    private BigDecimal USD_AMT;
    private BigDecimal WDRW_AMT;
    private String PFMC_BR_NO;
    private String VRTL_ACCT_NO;
    private String COMM_VOLN_PRIM_RSN_CTT;
    private String REG_EMP_NO;
    private Date REG_DT;
    private String REG_TM;
    private String UPD_EMP_NO;
    private Date UPD_DT;
    private String UPD_TM;

    public AFTR_FFH_COMM_TRSC_PTCL_DTO() {
    }
} 
