server:
  host: 118.70.245.192
  port: 22
  user: info_woori
  password: Infocity@123

path:
  fbk: /root/WRB_Gateway/
  fbkbackup: /root/WRB_Gateway/Complete/
  fbksend: /root/WRB_Gateway/Send/
  fbksendbk: /root/WRB_Gateway/SendBK/
  fbktowrb: /home/partner/INFO01/to_org
  fbkfromwrb: /home/partner/INFO01/from_org
  file:
    type: .dat
    header_snd: fbk_snd
    header_vir: fbk_vir
    header_awa: fbk_awa
    header_ccr: fbk_ccr